import { test, expect } from '@playwright/test'; 
test('Test-01: Duplicate Employee email trainee creation', async ({ page }) => { 
    await page.goto('https://hrmsqarightlyhr.onpremise.cluster.rightlyhr.com/login'); 
    await page.getByRole('textbox', { name: 'Please enter email' }).click(); 
    await page.getByRole('textbox', { name: 'Please enter email' }).fill('bhavitha.palagiri@snaddevelopers.com'); 
    await page.getByRole('textbox', { name: 'Please enter password' }).click(); 
    await page.getByRole('textbox', { name: 'Please enter password' }).press('CapsLock'); 
    await page.getByRole('textbox', { name: 'Please enter password' }).fill('B'); 
    await page.getByRole('textbox', { name: 'Please enter password' }).press('CapsLock'); 
    await page.getByRole('textbox', { name: 'Please enter password' }).fill('Bhavi@16'); 
    await page.getByRole('button', { name: 'Login' }).click(); 
    await page.getByText('Employees').click(); 
    // Click Employees
    await page.getByText('Employees', { exact: true }).click(); 
    console.log('Employees clicked'); 
    // Click Prospective
    await page.getByText('Prospective', { exact: true }).click(); 
    console.log('prospective clicked'); 
    // Click Trainees
    await page.locator('a[href="/employee-management/prospective/interns"]').click(); 
    console.log('Trainees clicked');
     await page.getByText('Employees', { exact: true }).click(); 
    await page.getByText('Prospective').click(); 
    console.log('prospective clicked'); 
    await page.getByRole('link', { name: 'Trainees (145)' }).click(); 
    await page.getByRole('button', { name: 'Add Prospective Trainee' }).click(); 
    await page.getByRole('textbox', { name: 'Please enter first name' }).click(); 
    await page.getByRole('textbox', { name: 'Please enter first name' }).press('CapsLock');
     await page.getByRole('textbox', { name: 'Please enter first name' }).fill('S'); 
     await page.getByRole('textbox', { name: 'Please enter first name' }).press('CapsLock'); 
     await page.getByRole('textbox', { name: 'Please enter first name' }).fill('Swetha'); 
     await page.getByRole('textbox', { name: 'Please enter last name' }).click();
      await page.getByRole('textbox', { name: 'Please enter last name' }).press('CapsLock'); 
      await page.getByRole('textbox', { name: 'Please enter last name' }).fill('P');
       await page.getByRole('textbox', { name: 'Please enter last name' }).press('CapsLock'); 
       await page.getByRole('textbox', { name: 'Please enter last name' }).fill('Priya'); 
       await page.getByRole('textbox', { name: 'Please enter personal email ID' }).click(); 
       await page.getByRole('textbox', { name: 'Please enter personal email ID' }).press('CapsLock'); 
       await page.getByRole('textbox', { name: 'Please enter personal email ID' }).fill('S'); 
       await page.getByRole('textbox', { name: 'Please enter personal email ID' }).press('CapsLock'); 
       await page.getByRole('textbox', { name: 'Please enter personal email ID' }).fill('Swethapriya@yopmail.com'); 
       await page.getByRole('combobox', { name: 'Please select designation' }).click(); 
       await page.getByRole('option', { name: 'Front End Developer' }).click(); 
       await page.getByRole('combobox', { name: 'Please select employment type' }).click(); 
       await page.getByText('Trainee', { exact: true }).click();
        await page.getByRole('combobox', { name: 'Please select location' }).click(); 
        await page.getByRole('option', { name: 'Hyderabad' }).click(); 
        await page.getByRole('combobox', { name: 'Please select sublocation' }).click(); 
        await page.getByText('Jai Hind Enclave building').click(); 
        await page.getByRole('button', { name: 'Add' }).click(); })
 test('Test-02: New trainee creation', async ({ page }) => {
     await page.goto('https://hrmsqarightlyhr.onpremise.cluster.rightlyhr.com/login'); 
     await page.getByRole('textbox', { name: 'Please enter email' }).click(); 
     await page.getByRole('textbox', { name: 'Please enter email' }).fill('bhavitha.palagiri@snaddevelopers.com'); 
     await page.getByRole('textbox', { name: 'Please enter password' }).click(); 
     await page.getByRole('textbox', { name: 'Please enter password' }).press('CapsLock');
      await page.getByRole('textbox', { name: 'Please enter password' }).fill('B'); 
      await page.getByRole('textbox', { name: 'Please enter password' }).press('CapsLock'); 
      await page.getByRole('textbox', { name: 'Please enter password' }).fill('Bhavi@16'); 
      await page.getByRole('button', { name: 'Login' }).click(); 
      await page.getByText('Employees').click(); 
      // Click Employees
      await page.getByText('Employees', { exact: true }).click(); console.log('Employees clicked'); 
      // Click Prospective
      await page.getByText('Prospective', { exact: true }).click(); 
      console.log('prospective clicked'); 
      // Click Trainees
      await page.locator('a[href="/employee-management/prospective/interns"]').click(); 
      console.log('Trainees clicked'); 
      await page.getByText('Employees', { exact: true }).click(); 
      await page.getByText('Prospective').click(); 
      console.log('prospective clicked');
       await page.getByRole('link', { name: 'Trainees (145)' }).click(); 
      await page.getByRole('button', { name: 'Add Prospective Trainee' }).click(); 
      await page.getByRole('textbox', { name: 'Please enter first name' }).click(); 
      await page.getByRole('textbox', { name: 'Please enter first name' }).press('CapsLock'); 
      await page.getByRole('textbox', { name: 'Please enter first name' }).fill('S'); 
      await page.getByRole('textbox', { name: 'Please enter first name' }).press('CapsLock'); 
      await page.getByRole('textbox', { name: 'Please enter first name' }).fill('Sindhuja'); 
      await page.getByRole('textbox', { name: 'Please enter last name' }).click(); 
      await page.getByRole('textbox', { name: 'Please enter last name' }).press('CapsLock');
       await page.getByRole('textbox', { name: 'Please enter last name' }).fill('P');
       await page.getByRole('textbox', { name: 'Please enter last name' }).press('CapsLock'); 
      await page.getByRole('textbox', { name: 'Please enter last name' }).fill('Priya');
       await page.getByRole('textbox', { name: 'Please enter personal email ID' }).click();
       await page.getByRole('textbox', { name: 'Please enter personal email ID' }).press('CapsLock'); 
      await page.getByRole('textbox', { name: 'Please enter personal email ID' }).fill('S'); 
      await page.getByRole('textbox', { name: 'Please enter personal email ID' }).press('CapsLock'); 
      await page.getByRole('textbox', { name: 'Please enter personal email ID' }).fill('Sindhuja@yopmail.com'); 
      await page.getByRole('combobox', { name: 'Please select designation' }).click();
       await page.getByRole('option', { name: 'Front End Developer' }).click(); 
      await page.getByRole('combobox', { name: 'Please select employment type' }).click(); 
      await page.getByText('Trainee', { exact: true }).click(); 
      await page.getByRole('combobox', { name: 'Please select location' }).click(); 
      await page.getByRole('option', { name: 'Hyderabad' }).click(); 
      await page.getByRole('combobox', { name: 'Please select sublocation' }).click(); 
      await page.getByText('Jai Hind Enclave building').click(); 
      await page.getByRole('button', { name: 'Add' }).click();
});

test('Test-03: Request documents and verify yopmail', async ({ page, context }) => {
      await page.goto('https://hrmsqarightlyhr.onpremise.cluster.rightlyhr.com/login');
      const page1 = await context.newPage();
      await page.getByText('Employee Created').first().click();
      await page.locator('body').press('ArrowLeft');
      await page.locator('body').press('ArrowLeft');
      await page.locator('body').press('ArrowLeft');
      await page.locator('body').press('ArrowLeft');
      await page.locator('body').press('ArrowLeft');
      await page.locator('body').press('ArrowLeft');
      await page.locator('body').press('ArrowLeft');
      await page.locator('body').press('ArrowLeft');
      await page.locator('body').press('ArrowLeft');
      await page.locator('body').press('ArrowLeft');
      await page.locator('body').press('ArrowLeft');
      await page.locator('body').press('ArrowLeft');
      await page.locator('body').press('ArrowLeft');
      await page.locator('body').press('ArrowLeft');
      await page.locator('body').press('ArrowLeft');
      await page.locator('body').press('ArrowLeft');
      await page.getByText('Sindhuja Priya').click();
      await page.getByRole('button', { name: 'Request for Documents' }).click();
      await page.getByText('Email has been sent').click();
      await page1.goto('https://yopmail.com/');
      await page1.getByRole('textbox', { name: 'Login' }).click();
      await page1.getByRole('textbox', { name: 'Login' }).fill('sindhuja');
      await page1.getByRole('textbox', { name: 'Login' }).click();
      await page1.getByRole('textbox', { name: 'Login' }).fill('sindhuja@yopmail.com');
      await page1.getByRole('textbox', { name: 'Login' }).press('Enter');
      await page1.getByTitle('Check Inbox @yopmail.com').click();
      await page1.locator('iframe[name="ifmail"]').contentFrame().getByText('RightlyHR - Sindhuja Priya').click();
      await page1.locator('iframe[name="ifmail"]').contentFrame().getByText('Username :').click();
      await page1.locator('iframe[name="ifmail"]').contentFrame().getByText('Password :').click();
      const page2Promise = page1.waitForEvent('popup');
      await page1.locator('iframe[name="ifmail"]').contentFrame().getByRole('link', { name: 'Click here' }).click();
      const page2 = await page2Promise;
      await page2.getByRole('textbox', { name: 'Username*' }).click();
      await page2.getByRole('textbox', { name: 'Username*' }).press('CapsLock');
      await page2.getByRole('textbox', { name: 'Username*' }).fill('S');
      await page2.getByRole('textbox', { name: 'Username*' }).press('CapsLock');
      await page2.getByRole('textbox', { name: 'Username*' }).fill('Sindhuja@yopmail.com');
      await page1.locator('iframe[name="ifmail"]').contentFrame().getByRole('cell', { name: 'Dear Sindhuja Priya, Welcome to the RightlyHR family! As part of your onboarding journey, we kindly request you to upload the documents listed below. This will help us ensure a smooth and timely onboarding process. Please be assured that all information provided will be handled with the highest level of confidentiality. You can access the onboarding portal using the credentials below: Portal Link : Click here Username : Sindhuja@yopmail.com Password : fsVB&iT! Documents Required: Aadhaar PAN Resume Thank you for choosing to begin your career journey with us! Best regards, RightlyHR', exact: true }).click();
      await page1.locator('iframe[name="ifmail"]').contentFrame().getByRole('cell', { name: 'Dear Sindhuja Priya, Welcome to the RightlyHR family! As part of your onboarding journey, we kindly request you to upload the documents listed below. This will help us ensure a smooth and timely onboarding process. Please be assured that all information provided will be handled with the highest level of confidentiality. You can access the onboarding portal using the credentials below: Portal Link : Click here Username : Sindhuja@yopmail.com Password : fsVB&iT! Documents Required: Aadhaar PAN Resume Thank you for choosing to begin your career journey with us! Best regards, RightlyHR', exact: true }).click();
      await page2.getByRole('textbox', { name: 'Password*' }).click();
      await page2.getByRole('textbox', { name: 'Password*' }).fill('fsVB&iT!');
      await page2.getByRole('button', { name: 'Login' }).click();
      await page2.locator('div').filter({ hasText: 'Application' }).nth(4).click();
      await page2.getByRole('button', { name: 'Go to Application' }).click();
      await page2.getByRole('combobox', { name: 'Please select gender' }).click();
      await page2.getByRole('option', { name: 'Female' }).click();
      await page2.getByRole('combobox', { name: 'Please select salutation' }).click();
      await page2.getByRole('option', { name: 'Miss.' }).click();
      await page2.getByText('Select country').click();
      await page2.locator('lib-country-list').getByRole('textbox').fill('91');
      await page2.getByText('India (भारत)').click();
      await page2.getByRole('textbox', { name: 'Please enter your mobile' }).click();
      await page2.getByRole('textbox', { name: 'Please enter your mobile' }).fill('8678567565');
      await page2.getByRole('textbox', { name: 'Date Of Birth *' }).fill('2000-03-02');
      await page2.getByRole('combobox', { name: 'Please select blood group' }).click();
      await page2.getByRole('option', { name: 'B+', exact: true }).click();
      await page2.locator('#currentAddressLine1').click();
      await page2.locator('#currentAddressLine1').press('CapsLock');
      await page2.locator('#currentAddressLine1').fill('R');
      await page2.locator('#currentAddressLine1').press('CapsLock');
      await page2.locator('#currentAddressLine1').fill('Road no.');
      await page2.locator('#currentAddressLine1').press('CapsLock');
      await page2.locator('#currentAddressLine1').fill('Road no.49');
      await page2.locator('#currentAddressLine1').press('CapsLock');
      await page2.locator('#currentAddressLine1').press('Tab');
      await page2.getByRole('textbox', { name: 'Address Line2' }).press('Tab');
      await page2.locator('#currentCity').press('CapsLock');
      await page2.locator('#currentCity').fill('H');
      await page2.locator('#currentCity').press('CapsLock');
      await page2.locator('#currentCity').fill('Hyderabad');
      await page2.locator('#currentState').click();
      await page2.locator('#currentState').press('CapsLock');
      await page2.locator('#currentState').fill('T');
      await page2.locator('#currentState').press('CapsLock');
      await page2.locator('#currentState').fill('Telangana');
      await page2.getByRole('textbox', { name: 'Country*' }).click();
      await page2.getByRole('textbox', { name: 'Country*' }).press('CapsLock');
      await page2.getByRole('textbox', { name: 'Country*' }).fill('I');
      await page2.getByRole('textbox', { name: 'Country*' }).press('CapsLock');
      await page2.getByRole('textbox', { name: 'Country*' }).fill('India');
      await page2.locator('#currentzipCode').click();
      await page2.locator('#currentzipCode').fill('500012');
      await page2.getByRole('checkbox', { name: 'Same as Current Address' }).check();
      await page2.getByRole('button', { name: 'Next' }).click();
      await page2.getByRole('row', { name: 'Resume* - - - Requested' }).getByRole('button').click();
      await page2.getByRole('button', { name: 'Choose File' }).setInputFiles('Ridhesh__Kumar_1788248807267_Non-DisclosureAgreementLeter_Signed.pdf');
      await page2.getByRole('textbox', { name: 'Document Number' }).click();
      await page2.getByRole('button', { name: 'Upload' }).click();
      await page2.getByRole('row', { name: 'PAN* - - - Requested - - ' }).getByRole('button').click();
      await page2.getByRole('textbox', { name: 'Document Number*' }).click();
      await page2.getByRole('textbox', { name: 'Document Number*' }).press('CapsLock');
      await page2.getByRole('textbox', { name: 'Document Number*' }).fill('EDGDD5645H');
      await page2.getByRole('button', { name: 'Choose File' }).setInputFiles('Ridhesh__Kumar_1788248721927_Non-DisclosureAgreementLetter_Unsigned.pdf');
      await page2.getByRole('button', { name: 'Upload' }).click();
      await page2.getByRole('button', { name: ' Upload' }).click();
      await page2.getByRole('textbox', { name: 'Document Number*' }).click();
      await page2.getByRole('textbox', { name: 'Document Number*' }).fill('877867686786');
      await page2.getByRole('button', { name: 'Choose File' }).setInputFiles('Ridhesh__Kumar_1788247985340_OfferLetter_Signed.pdf');
      await page2.getByRole('button', { name: 'Upload' }).click();
      await page2.getByText('Document uploaded successfully').click();
      await page2.getByRole('button', { name: 'Submit' }).click();
      await page2.getByText('Are you sure you want to').click();
      await page2.getByText('Close Submit').click();
      await page2.getByRole('button', { name: 'Submit' }).click();
      await page2.getByText('Submitted successfully, We’ll').click();
      await page1.locator('iframe[name="ifmail"]').contentFrame().getByText('RightlyHR - Sindhuja Priya -').click();
      await page1.locator('iframe[name="ifmail"]').contentFrame().getByRole('cell', { name: 'Company Logo Image Dear' }).nth(1).click();
      await page.getByText('Job').click();
      await page.locator('div').filter({ hasText: /^Onboarding Documents$/ }).nth(1).click();
      await page.locator('.dropdown > a').first().click();
      await page.locator('.dropdown > a').first().click();
      await page.locator('.dropdown > a').first().click();
      await page.locator('.dropdown > a').first().click();
      await page.locator('.dropdown > a').first().click();
      await page.locator('.dropdown.ng-star-inserted').first().click();
      await page.locator('body').press('ArrowDown');
      await page.locator('body').press('ArrowDown');
      await page.locator('body').press('ArrowDown');
      await page.getByText('Reject').first().click();
      await page.getByRole('textbox', { name: 'Please enter reject reason' }).click();
      await page.getByRole('textbox', { name: 'Please enter reject reason' }).press('CapsLock');
      await page.getByRole('textbox', { name: 'Please enter reject reason' }).fill('r');
      await page.getByRole('textbox', { name: 'Please enter reject reason' }).press('CapsLock');
      await page.getByRole('textbox', { name: 'Please enter reject reason' }).fill('R');
      await page.getByRole('textbox', { name: 'Please enter reject reason' }).press('CapsLock');
      await page.getByRole('textbox', { name: 'Please enter reject reason' }).fill('Rejected ');
      await page.getByText('Close Reject').click();
      await page.getByRole('button', { name: 'Reject' }).click();
      await page.getByText('Document rejected successfully').click();
      await page.locator('tr:nth-child(2) > .text-center.ng-star-inserted > .dropdown > a').click();
      await page.locator('tr:nth-child(2) > .text-center.ng-star-inserted > .dropdown > a').click();
      await page.locator('tr:nth-child(2) > .text-center.ng-star-inserted > .dropdown > a').click();
      await page.locator('tr:nth-child(2) > .text-center.ng-star-inserted > .dropdown > a').click();
      await page.locator('tr:nth-child(2) > .text-center.ng-star-inserted > .dropdown > a').click();
      await page.locator('tr:nth-child(2) > .text-center.ng-star-inserted > .dropdown > a').click();
      await page.getByRole('cell').filter({ hasText: 'VerifyReject' }).nth(1).click();
      await page.getByText('Verify').nth(1).click();
      await page.getByText('Are you sure you want to').click();
      await page.getByText('NoYes').click();
      await page.getByRole('button', { name: 'Yes' }).click();
      await page.getByText('Document verified successfully').click();
      await page.locator('.dropdown > a').click();
      await page.getByRole('cell').filter({ hasText: 'VerifyReject' }).click();
      await page.getByText('Verify').click();
      await page.getByText('Are you sure you want to').click();
      await page.getByRole('button', { name: 'Yes' }).click();
      await page.getByText('Document verified successfully').click();
      await page.getByRole('button', { name: 'Re-Request Documents' }).click();
      await page.getByRole('textbox', { name: 'Please enter comments' }).click();
      await page.getByRole('textbox', { name: 'Please enter comments' }).press('CapsLock');
      await page.getByRole('textbox', { name: 'Please enter comments' }).fill('R');
      await page.getByRole('textbox', { name: 'Please enter comments' }).press('CapsLock');
      await page.getByRole('textbox', { name: 'Please enter comments' }).fill('Rerequest the rejected documents');
      await page.getByText('CloseSubmit').click();
      await page.getByRole('button', { name: 'Re-Request Documents' }).click();
      await page.getByRole('textbox', { name: 'Please enter comments' }).click();
      await page.getByRole('textbox', { name: 'Please enter comments' }).fill('rerequest rejected documents');
      await page.getByRole('button', { name: 'Submit' }).click();
      await page.getByText('Email has been sent').click();
      await page1.locator('#refresh').click();
      await page1.locator('iframe[name="ifmail"]').contentFrame().getByText('Deliverability Reply').click();
      await page1.locator('iframe[name="ifmail"]').contentFrame().getByText('RightlyHR - Sindhuja Priya -').click();
      await page1.locator('iframe[name="ifmail"]').contentFrame().getByRole('cell', { name: 'Company Logo Image Dear' }).nth(1).click();
      await page1.locator('iframe[name="ifmail"]').contentFrame().getByText('Comments :').click();
      await page1.locator('iframe[name="ifmail"]').contentFrame().getByText('Username :').click();
      await page1.locator('iframe[name="ifmail"]').contentFrame().getByText('Password :').click();
      const page3Promise = page1.waitForEvent('popup');
      await page1.locator('iframe[name="ifmail"]').contentFrame().getByRole('link', { name: 'Click here' }).click();
      const page3 = await page3Promise;
      await page3.getByRole('textbox', { name: 'Username*' }).click();
      await page3.getByRole('textbox', { name: 'Username*' }).click();
      await page3.getByRole('textbox', { name: 'Username*' }).press('CapsLock');
      await page3.getByRole('textbox', { name: 'Username*' }).fill('S');
      await page3.getByRole('textbox', { name: 'Username*' }).press('CapsLock');
      await page3.getByRole('textbox', { name: 'Username*' }).fill('Sinshuja@yopmail.com');
      await page3.getByRole('textbox', { name: 'Username*' }).dblclick();
      await page3.getByRole('textbox', { name: 'Username*' }).click();
      await page3.getByRole('textbox', { name: 'Username*' }).fill('Sindhuja@yopmail.com');
      await page3.locator('div:nth-child(2) > .input-group').click();
      await page1.locator('iframe[name="ifmail"]').contentFrame().getByText('Password :').click();
      await page3.getByRole('textbox', { name: 'Password*' }).click();
      await page3.getByRole('textbox', { name: 'Password*' }).fill('fsVB&iT!');
      await page3.locator('i').click();
      await page3.getByRole('textbox', { name: 'Password*' }).click();
      await page3.getByRole('button', { name: 'Login' }).click();
      await page3.getByRole('button', { name: 'Go to Application' }).click();
      await page3.getByRole('button', { name: 'Next' }).click();
      await page3.locator('a').nth(4).click();
      await page3.getByRole('button', { name: ' Re-Upload' }).click();
      await page3.getByRole('button', { name: 'Choose File' }).setInputFiles('Ridhesh__Kumar_1788248721927_Non-DisclosureAgreementLetter_Unsigned.pdf');
      await page3.getByText('Note: Only Pdf and image are').click();
      await page3.getByRole('button', { name: 'Upload' }).click();
      await page3.getByText('Document uploaded successfully').click();
      await page3.getByRole('button', { name: 'Submit' }).click();
      await page3.getByText('Are you sure you want to').click();
      await page3.getByRole('button', { name: 'Submit' }).click();
      await page1.locator('#refresh').click();
      await page1.locator('iframe[name="ifmail"]').contentFrame().getByText('RightlyHR - Sindhuja Priya -').click();
      await page1.locator('iframe[name="ifmail"]').contentFrame().getByRole('cell', { name: 'Company Logo Image Dear' }).nth(1).click();
      await page.getByRole('cell').filter({ hasText: 'VerifyReject' }).click();
      await page.getByText('Verify').click();
      await page.getByText('Are you sure you want to').click();
      await page.getByRole('button', { name: 'Yes' }).click();
      await page.getByText('Document verified successfully').click();
});

test('test07', async ({ page }) => {
  await page.goto('https://hrmsqarightlyhr.onpremise.cluster.rightlyhr.com/login');
  await page.getByText('Employees').click();
  await page.getByRole('button', { name: 'Generate Documents' }).click();
  await page.locator('div').filter({ hasText: /^Trainee Offer Letter$/ }).first().click();
  await page.locator('#pn_id_7').getByRole('button', { name: 'dropdown trigger' }).click();
  await page.locator('#pn_id_7').getByRole('button', { name: 'dropdown trigger' }).click();
  await page.getByRole('searchbox', { name: 'Search employee' }).click();
  await page.getByRole('searchbox', { name: 'Search employee' }).fill('sin');
  await page.getByRole('option', { name: '- Sindhuja Priya' }).click();
  await page.getByText('Personal Email ID*').click();
  await page.getByText('Salutation*').click();
  await page.getByText('Salutation*').click();
  await page.getByText('First Name*').click();
  await page.getByText('Middle Name').click();
  await page.getByText('Last Name*').click();
  await page.getByText('Gender*').click();
  await page.locator('div').filter({ hasText: /^Female$/ }).click();
  await page.getByText('Select Address *').click();
  await page.locator('#pn_id_13').getByRole('button', { name: 'dropdown trigger' }).click();
  await page.getByRole('option', { name: 'Current Address' }).click();
  await page.getByText('Address Line 1*').click();
  await page.getByText('Address Line 2').click();
  await page.locator('div').filter({ hasText: /^City\*$/ }).click();
  await page.locator('div').filter({ hasText: /^State\*$/ }).click();
  await page.locator('div').filter({ hasText: /^Country\*$/ }).click();
  await page.locator('div').filter({ hasText: /^Pincode\*$/ }).click();
  await page.getByText('Mobile Number with Country').click();
  await page.locator('.d-flex.custom-input-group').click();
  await page.locator('div:nth-child(16)').click();
  await page.getByText('Salary (Cost to Company)*').click();
  await page.getByRole('spinbutton', { name: 'Please enter salary' }).click();
  await page.getByRole('spinbutton', { name: 'Please enter salary' }).fill('400000');
  await page.getByRole('spinbutton', { name: 'Please enter salary' }).click();
  await page.getByRole('spinbutton', { name: 'Please enter salary' }).fill('0');
  await page.getByText('Work Location*Hyderabad').click();
  await page.getByRole('spinbutton', { name: 'Please enter salary' }).click();
  await page.getByRole('spinbutton', { name: 'Please enter salary' }).fill('-200000');
  await page.getByText('Select Employee*12759 - Sindhuja PriyaPersonal Email ID*Salutation*Miss.First').click();
  await page.locator('div').filter({ hasText: /^Hyderabad$/ }).click();
  await page.getByText('Work Location*').click();
  await page.getByRole('spinbutton', { name: 'Please enter salary' }).click();
  await page.getByRole('spinbutton', { name: 'Please enter salary' }).click();
  await page.getByRole('spinbutton', { name: 'Please enter salary' }).press('ArrowLeft');
  await page.getByRole('spinbutton', { name: 'Please enter salary' }).press('ArrowLeft');
  await page.getByRole('spinbutton', { name: 'Please enter salary' }).press('ArrowLeft');
  await page.getByRole('spinbutton', { name: 'Please enter salary' }).press('ArrowLeft');
  await page.getByRole('spinbutton', { name: 'Please enter salary' }).press('ArrowLeft');
  await page.getByRole('spinbutton', { name: 'Please enter salary' }).press('ArrowLeft');
  await page.getByRole('spinbutton', { name: 'Please enter salary' }).press('ArrowLeft');
  await page.getByRole('spinbutton', { name: 'Please enter salary' }).press('ArrowRight');
  await page.getByRole('spinbutton', { name: 'Please enter salary' }).fill('200000');
  await page.getByText('Work Location*Hyderabad').click();
  await page.getByText('Sub Location*Jai Hind Enclave').click();
  await page.getByText('Offer Issued Date*').click();
  await page.getByPlaceholder('Please enter offer issued date').fill('2026-09-03');
  await page.getByPlaceholder('Please enter expected start').fill('2026-09-03');
  await page.getByPlaceholder('Please enter offer expiry date').fill('2026-09-02');
  await page.getByText('Offer Expiry Date should be').click();
  await page.getByText('Offer Expiry Date should be').click();
  await page.getByPlaceholder('Please enter offer expiry date').fill('2026-09-03');
  await page.getByText('Training Period(Months)*').click();
  await page.locator('#pn_id_19 > .p-select-dropdown').click();
  await page.getByRole('option', { name: '1' }).click();
  await page.getByText('Reporting Manager *Please').click();
  await page.locator('#pn_id_21 > .p-select-dropdown').click();
  await page.locator('#pn_id_21 > .p-select-dropdown').click();
  await page.getByRole('searchbox').fill('bhav');
  await page.getByText('SD302135 - Bhavitha Reddy').click();
  await page.locator('#pn_id_23 > .p-select-dropdown').click();
  await page.getByRole('option', { name: 'Soft Copy' }).click();
  await page.locator('.d-flex.justify-content-end').first().click();
  await page.locator('.letter-footer').first().click();
  await page.locator('#pn_id_23 > .p-select-dropdown').click();
  await page.getByRole('option', { name: 'Soft Copy' }).click();
  await page.locator('#pn_id_23 > .p-select-dropdown').click();
  await page.getByRole('option', { name: 'Hard Copy' }).click();
  await page.getByText('Trainee Offer LetterSindhuja').click();
  await page.locator('#pn_id_25 > .p-select-dropdown').click();
  await page.locator('#pn_id_25 > .p-select-dropdown').click();
  await page.getByRole('option', { name: 'saii Pavan Dinesh Tejaa' }).click();
  await page.getByRole('textbox', { name: 'Please enter note' }).click();
  await page.getByRole('textbox', { name: 'Please enter note' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Please enter note' }).fill('T');
  await page.getByRole('textbox', { name: 'Please enter note' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Please enter note' }).fill('Trainee ');
  await page.getByRole('textbox', { name: 'Please enter note' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Please enter note' }).fill('Trainee O');
  await page.getByRole('textbox', { name: 'Please enter note' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Please enter note' }).fill('Trainee Offer letter');
  await page.getByText('Note20/').click();
  await page.getByText('Note: Trainee Offer letter').click();
  await page.locator('.letter-sub-data-content > div').click();
  const downloadPromise = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Generate Offer Letter' }).click();
  const download = await downloadPromise;
  await page.getByText('Trainee Offer letter generated successfully').click();
  const download1Promise = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Generate Offer Letter' }).click();
  const download1 = await download1Promise;
  await page.locator('div').filter({ hasText: 'Trainee Offer letter generated successfully' }).nth(3).click();
  await page.getByRole('paragraph').filter({ hasText: /^saii Pavan Dinesh Tejaa$/ }).click();
  await page.getByRole('button', { name: 'Request For Approval' }).click();
  await page.getByText('Approval request sent').click();
}
import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://hrmsqarightlyhr.onpremise.cluster.rightlyhr.com/dashboard/emp');
  await page.getByText('Pending Approvals').click();
  await page.getByText('Onboarding(7)').click();
  await page.getByText('Trainee Offer Letter(2)').click();
  await page.getByRole('cell', { name: 'Sindhuja Priya' }).click();
  await page.getByRole('cell', { name: 'Sep 3,' }).nth(1).click();
  await page.getByRole('cell', { name: 'Sindhuja Priya' }).click();
  await page.getByRole('cell', { name: 'Hyderabad' }).nth(1).click();
  await page.getByRole('cell', { name: 'Jai Hind Enclave building' }).nth(1).click();
  await page.getByRole('cell', { name: 'Front End Developer' }).nth(1).click();
  await page.getByRole('cell', { name: '30' }).nth(1).click();
  await page.getByRole('cell', { name: 'Waiting For Approval' }).nth(1).click();
  await page.getByRole('cell', { name: 'Offer Letter Generated' }).nth(1).click();
  await page.locator('body').press('ArrowRight');
  await page.locator('body').press('ArrowRight');
  await page.locator('body').press('ArrowRight');
  await page.locator('body').press('ArrowRight');
  await page.getByRole('columnheader', { name: 'Action' }).click();
  await page.locator('tr:nth-child(2) > .text-center > .dropdown > a').click();
  const downloadPromise = page.waitForEvent('download');
  await page.getByText('Download').nth(1).click();
  const download = await downloadPromise;
  await page.locator('tr:nth-child(2) > .text-center > .dropdown > a').click();
  await page.getByText('Reject').nth(1).click();
  await page.getByText('Reject Reason', { exact: true }).click();
  await page.getByText('Reject Reason*0 /').click();
  await page.getByRole('textbox', { name: 'Please provide reject reason' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Please provide reject reason' }).fill('R');
  await page.getByRole('textbox', { name: 'Please provide reject reason' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Please provide reject reason' }).fill('Rejected ');
  await page.getByRole('textbox', { name: 'Please provide reject reason' }).click();
  await page.getByRole('textbox', { name: 'Please provide reject reason' }).fill('Rejected Rejected Rejected Rejected Rejected Rejected Rejected Rejected Rejected Rejected Rejected Rejected Rejected Rejected Rejected Rejected Rejected Rejected Rejected Rejected Rejected Rejected Rejected Rejected Rejected Rejected Rejected Rejecte');
  await page.getByText('/ 250').click();
  await page.getByRole('button', { name: 'Reject' }).click();
  await page.getByText('Trainee offer letter rejected').click();
  await page.locator('#cdk-drop-list-6').getByText('(1)').click();
  await page1.getByText('Sindhuja Priya Offer Letter').click();
  await page1.getByRole('heading', { name: 'Sindhuja Priya Offer Letter', description: 'Sindhuja Priya Offer Letter Not Approved by Bhavitha Reddy' }).click();
  await page1.locator('[data-test-id="mailMessageBodyContainer"]').click();
});
import { test, expect } from '@playwright/test';

test('test10', async ({ page }) => {
  await page.goto('https://hrmsqarightlyhr.onpremise.cluster.rightlyhr.com/login');
  await page.getByText('Pending Approvals').click();
  await page.getByText('Onboarding').click();
  await page.locator('li:nth-child(3) > .nav-link > .icon').click();
  await page.locator('body').press('ArrowRight');
  await page.locator('body').press('ArrowRight');
  await page.locator('a').nth(3).click();
  await page.getByText('Approve').click();
  await page.getByText('Trainee Offer approved').click();
  await page1.getByLabel('Unread Test Snad Karthik Verma Offer Letter Approved by Bhavitha Reddy 2:46 PM').locator('div').filter({ hasText: /^Test Snad$/ }).click();
  await page1.getByLabel('Unread Test Snad Karthik Verma Offer Letter Approved by Bhavitha Reddy 2:46 PM').locator('div').filter({ hasText: /^Test Snad$/ }).click();
  await page1.getByRole('heading', { name: 'Karthik Verma Offer Letter', description: 'Karthik Verma Offer Letter Approved by Bhavitha Reddy' }).click();
  await page1.getByRole('cell', { name: 'Company Logo Image Dear' }).nth(1).click();
  await page.locator('div').filter({ hasText: /^DownloadRelease Offer$/ }).click();
  await page.getByText('Release Offer').click();
  await page.getByText('Intern offer letter released').click();
});

import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://hrmsqarightlyhr.onpremise.cluster.rightlyhr.com/login');
  await page.getByText('Employees').click();
  await page.getByRole('button', { name: 'Generate Documents' }).click();
  await page.locator('div').filter({ hasText: /^Trainee Offer Letter$/ }).first().click();
  await page.locator('#pn_id_7').getByRole('button', { name: 'dropdown trigger' }).click();
  await page.getByRole('option', { name: '- Nandini Joshi' }).click();
  await page.getByRole('combobox', { name: 'Please select address' }).click();
  await page.getByRole('option', { name: 'Current Address' }).click();
  await page.getByRole('spinbutton', { name: 'Please enter salary' }).click();
  await page.getByRole('spinbutton', { name: 'Please enter salary' }).fill('350000');
  await page.getByPlaceholder('Please enter offer issued date').fill('2026-09-03');
  await page.getByPlaceholder('Please enter offer expiry date').fill('2026-09-03');
  await page.locator('#pn_id_19 > .p-select-dropdown').click();
  await page.getByRole('option', { name: '1' }).click();
  await page.getByRole('combobox', { name: 'Please select document type' }).click();
  await page.getByRole('option', { name: 'Soft Copy' }).click();
  await page.getByRole('combobox', { name: 'Please select signature' }).click();
  await page.getByText('Ganesh Babu').click();
  const downloadPromise = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Regenerate Offer Letter' }).click();
  const download = await downloadPromise;
  await page.getByRole('button', { name: 'Request For Approval' }).click();
  await page.locator('.cdk-drag.nav-item.menu-item-clear.draggable-nav-item.ng-star-inserted.active-nav-link > .btn-group > div > .main-menu-icon').click();
  await page.locator('#sidenav-main-drop').getByText('Onboarding').click();
  await page.getByText('Trainee Offer Letter').click();
  await page.getByRole('cell', { name: 'Waiting For Approval' }).click();
  await page.locator('body').press('ArrowRight');
  await page.locator('body').press('ArrowRight');
  await page.locator('body').press('ArrowRight');
  await page.locator('body').press('ArrowRight');
  await page.locator('a').nth(3).click();
  await page.getByText('Approve').click();
  await page.getByRole('dialog').press('ArrowRight');
  await page.getByRole('dialog').press('ArrowRight');
  await page.locator('#sidenav-main-drop').getByText('Pending Approvals').click();
  await page.locator('#sidenav-main-drop').getByText('Onboarding').click();
  await page.getByText('Trainee Offer Letter').click();
  await page.locator('body').press('ArrowRight');
  await page.locator('body').press('ArrowRight');
  await page.locator('div').filter({ hasText: /^DownloadRelease Offer$/ }).click();
  await page.getByText('Release Offer').click();
  await page.getByText('Intern offer letter released').click();
  await page1.goto('https://yopmail.com/');
  await page1.getByRole('textbox', { name: 'Login' }).click();
  await page1.getByRole('textbox', { name: 'Login' }).fill('\tnandini.joshi.ijt@yopmail.com');
  await page1.getByTitle('Check Inbox @yopmail.com').click();
  const page2Promise = page1.waitForEvent('popup');
  await page1.locator('iframe[name="ifmail"]').contentFrame().getByRole('link', { name: 'Click here' }).click();
  const page2 = await page2Promise;
  await page2.getByRole('textbox', { name: 'Username*' }).click();
  await page2.getByRole('textbox', { name: 'Username*' }).fill('\tnandini.joshi.ijt@yopmail.com');
  await page2.locator('div:nth-child(2) > .input-group').click();
  await page2.getByRole('textbox', { name: 'Password*' }).fill('dFq4u13v');
  await page2.getByRole('button', { name: 'Login' }).click();
  await page2.getByRole('textbox', { name: 'Password*' }).click();
  await page2.getByRole('textbox', { name: 'Password*' }).click();
  await page2.getByRole('textbox', { name: 'Password*' }).fill('y%97TCTb');
  await page2.getByRole('button', { name: 'Login' }).click();
  await page2.getByRole('button', { name: 'Go to Application' }).click();
  await page2.getByRole('button', { name: 'Next' }).click();
  await page2.getByRole('button', { name: 'Next' }).click();
  await page2.getByRole('button', { name: 'Accept' }).click();
  await page2.getByRole('button', { name: 'Yes' }).click();
  await page2.getByText('Offer letter accepted').click();
  const download1Promise = page2.waitForEvent('download');
  await page2.getByRole('button', { name: 'Download' }).click();
  const download1 = await download1Promise;
  await page2.getByRole('button', { name: 'Next' }).click();
  await page2.getByRole('button', { name: 'Add' }).click();
  await page2.getByRole('button', { name: 'dropdown trigger' }).click();
  await page2.getByRole('option', { name: 'B.TECH' }).click();
  await page2.getByRole('textbox', { name: 'University*' }).click();
  await page2.getByRole('textbox', { name: 'University*' }).press('CapsLock');
  await page2.getByRole('textbox', { name: 'University*' }).fill('C');
  await page2.getByRole('textbox', { name: 'University*' }).press('CapsLock');
  await page2.getByRole('textbox', { name: 'University*' }).fill('California ');
  await page2.getByRole('textbox', { name: 'University*' }).press('CapsLock');
  await page2.getByRole('textbox', { name: 'University*' }).fill('California U');
  await page2.getByRole('textbox', { name: 'University*' }).press('CapsLock');
  await page2.getByRole('textbox', { name: 'University*' }).fill('California Unversity');
  await page2.getByRole('textbox', { name: 'Specialization*' }).click();
  await page2.getByRole('textbox', { name: 'Specialization*' }).press('CapsLock');
  await page2.getByRole('textbox', { name: 'Specialization*' }).fill('CSE');
  await page2.getByRole('textbox', { name: 'Specialization*' }).press('CapsLock');
  await page2.getByRole('spinbutton', { name: 'GPA*' }).click();
  await page2.getByRole('spinbutton', { name: 'GPA*' }).fill('7');
  await page2.getByRole('textbox', { name: 'Start Date*' }).fill('2020-06-09');
  await page2.getByRole('textbox', { name: 'To Date*' }).fill('2024-01-30');
  await page2.getByRole('button', { name: 'Attachment (Upload the Image' }).setInputFiles('Tejaswi__Naidu_1788415253496_OfferLetter.pdf');
  await page2.getByRole('button', { name: 'Add' }).click();
  await page2.locator('div').filter({ hasText: 'Academic record added' }).nth(3).click();
  await page2.getByRole('button', { name: 'Next' }).click();
  await page2.getByRole('textbox', { name: 'Please enter name' }).first().click();
  await page2.getByRole('textbox', { name: 'Please enter name' }).first().press('CapsLock');
  await page2.getByRole('textbox', { name: 'Please enter name' }).first().fill('R');
  await page2.getByRole('textbox', { name: 'Please enter name' }).first().press('CapsLock');
  await page2.getByRole('textbox', { name: 'Please enter name' }).first().fill('Ravi');
  await page2.getByRole('textbox', { name: 'Please enter name' }).first().press('Tab');
  await page2.getByRole('textbox', { name: 'Please enter personal email ID' }).first().press('CapsLock');
  await page2.getByRole('textbox', { name: 'Please enter personal email ID' }).first().fill('R');
  await page2.getByRole('textbox', { name: 'Please enter personal email ID' }).first().press('CapsLock');
  await page2.getByRole('textbox', { name: 'Please enter personal email ID' }).first().fill('Ravi@yopmail.com');
  await page2.getByText('Select country').first().click();
  await page2.getByRole('textbox').nth(2).fill('91');
  await page2.getByRole('listbox').getByText('India (भारत)').click();
  await page2.getByRole('spinbutton', { name: 'Please enter mobile number' }).first().click();
  await page2.getByRole('spinbutton', { name: 'Please enter mobile number' }).first().fill('9567564564');
  await page2.locator('#pn_id_6').getByRole('combobox', { name: 'Please select relation' }).click();
  await page2.getByRole('option', { name: 'Brother', exact: true }).click();
  await page2.getByRole('textbox', { name: 'Please enter name' }).nth(1).click();
  await page2.getByRole('textbox', { name: 'Please enter name' }).nth(1).press('CapsLock');
  await page2.getByRole('textbox', { name: 'Please enter name' }).nth(1).fill('S');
  await page2.getByRole('textbox', { name: 'Please enter name' }).nth(1).press('CapsLock');
  await page2.getByRole('textbox', { name: 'Please enter name' }).nth(1).fill('Sindhu');
  await page2.getByRole('textbox', { name: 'Please enter personal email ID' }).nth(1).click();
  await page2.getByRole('textbox', { name: 'Please enter personal email ID' }).nth(1).press('CapsLock');
  await page2.getByRole('textbox', { name: 'Please enter personal email ID' }).nth(1).fill('S');
  await page2.getByRole('textbox', { name: 'Please enter personal email ID' }).nth(1).press('CapsLock');
  await page2.getByRole('textbox', { name: 'Please enter personal email ID' }).nth(1).fill('Sindhu@yopmail.com');
  await page2.getByText('Select country').click();
  await page2.locator('lib-country-list').filter({ hasText: 'Select countryAfghanistan' }).getByRole('textbox').fill('91');
  await page2.getByRole('listbox').getByText('India (भारत)').click();
  await page2.getByRole('spinbutton', { name: 'Please enter mobile number' }).nth(1).click();
  await page2.getByRole('spinbutton', { name: 'Please enter mobile number' }).nth(1).fill('8456757477');
  await page2.getByRole('combobox', { name: 'Please select relation' }).click();
  await page2.getByRole('option', { name: 'Mother' }).click();
  await page2.getByRole('button', { name: 'Next' }).click();
  await page2.getByRole('button', { name: 'Add' }).click();
  await page2.getByRole('textbox', { name: 'Company Name' }).click();
  await page2.getByRole('textbox', { name: 'Company Name' }).press('CapsLock');
  await page2.getByRole('textbox', { name: 'Company Name' }).fill('SNAD');
  await page2.getByRole('textbox', { name: 'Company Name' }).press('CapsLock');
  await page2.getByRole('combobox', { name: 'Please select employment type' }).click();
  await page2.locator('#pn_id_10_1').click();
  await page2.getByPlaceholder('From Date').fill('2023-01-09');
  await page2.getByRole('textbox').nth(2).fill('2026-01-12');
  await page2.getByRole('textbox', { name: 'Job Role' }).click();
  await page2.getByRole('textbox', { name: 'Job Role' }).press('CapsLock');
  await page2.getByRole('textbox', { name: 'Job Role' }).fill('QA');
  await page2.getByRole('textbox', { name: 'Job Role' }).press('CapsLock');
  await page2.getByRole('button', { name: 'Choose File' }).setInputFiles('Tejaswi__Naidu_1788415253496_OfferLetter.pdf');
  await page2.getByRole('button', { name: 'Choose File' }).setInputFiles('Compensation_1.xls');
  await page2.getByRole('button', { name: 'Choose File' }).setInputFiles('Call with Anusha Koyya-20260721_112955-Meeting Recording.mp4');
  await page2.getByRole('button', { name: 'Choose File' }).setInputFiles('Tejaswi__Naidu_1788415253496_OfferLetter.pdf');
  await page2.getByRole('button', { name: 'Add' }).click();
  await page2.getByText('Employment history added').click();
  await page2.getByRole('button', { name: 'Next' }).click();
  await page2.locator('div').filter({ hasText: /^Review$/ }).click();
  await page2.locator('.accordion-body').first().click();
  await page2.getByRole('button', { name: 'Academic Qualifications' }).click();
  await page2.getByRole('button', { name: 'Academic Qualifications' }).click();
  await page2.getByRole('heading', { name: 'Employment History' }).getByRole('button').click();
  await page2.getByRole('heading', { name: 'Employment History' }).getByRole('button').click();
  await page2.locator('div').filter({ hasText: /^Offer Letter Accepted$/ }).dblclick();
  await page2.getByRole('button', { name: 'Submit' }).click();
  await page2.getByRole('button', { name: 'Yes' }).click();
  await page2.getByRole('button', { name: 'Close' }).click();
  await page.getByText('Employees').click();
  await page.getByText('Employees').click();
  await page.getByText('Employees', { exact: true }).click();
  await page.getByText('Prospective(813)').click();
  await page.getByRole('searchbox', { name: 'Username' }).click();
  await page.getByRole('searchbox', { name: 'Username' }).fill('josh');
  await page.getByRole('link', { name: 'Trainees (172)' }).click();
  await page.getByRole('searchbox', { name: 'Username' }).click();
  await page.getByRole('searchbox', { name: 'Username' }).fill('jo');
  await page.getByRole('searchbox', { name: 'Username' }).press('ArrowRight');
  await page.getByRole('cell', { name: '+91 9442344383' }).click();
  await page.locator('body').press('ArrowRight');
  await page.locator('body').press('ArrowRight');
  await page.locator('body').press('ArrowRight');
  await page.locator('body').press('ArrowRight');
  await page.locator('body').press('ArrowRight');
  await page.locator('body').press('ArrowRight');
  await page.locator('body').press('ArrowRight');
  await page.locator('body').press('ArrowRight');
  await page.locator('body').press('ArrowRight');
  await page.locator('body').press('ArrowRight');
  await page.locator('body').press('ArrowRight');
  await page.locator('body').press('ArrowRight');
  await page.locator('body').press('ArrowRight');
  await page.locator('body').press('ArrowRight');
  await page.locator('body').press('ArrowRight');
  await page.locator('body').press('ArrowRight');
  await page.locator('body').press('ArrowRight');
  await page.locator('body').press('ArrowRight');
  await page.locator('body').press('ArrowRight');
  await page.locator('body').press('ArrowRight');
  await page.locator('body').press('ArrowRight');
  await page.locator('body').press('ArrowRight');
  await page.locator('body').press('ArrowRight');
  await page.locator('body').press('ArrowRight');
  await page.getByText('Offer Letter Accepted').click();
});

import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://hrmsqarightlyhr.onpremise.cluster.rightlyhr.com/login');
  await page.getByText('Employees').click();
  await page.getByText('Prospective(813)').click();
  await page.getByRole('link', { name: 'Trainees (172)' }).click();
  await page.getByRole('searchbox', { name: 'Username' }).click();
  await page.getByRole('searchbox', { name: 'Username' }).fill('');
  await page.getByRole('cell', { name: 'Sindhuja Priya' }).click();
  await page.getByText('Prospective Trainee').click();
  await page.locator('body').press('ArrowRight');
  await page.locator('body').press('ArrowRight');
  await page.getByRole('columnheader', { name: 'Phone Number' }).click();
  await page.getByRole('searchbox', { name: 'Username' }).click();
  await page.getByRole('searchbox', { name: 'Username' }).fill('sin');
  await page.locator('#pn_id_8').click();
  await page.locator('body').press('ArrowRight');
  await page.locator('body').press('ArrowRight');
  await page.locator('body').press('ArrowRight');
  await page.locator('body').press('ArrowRight');
  await page.locator('body').press('ArrowRight');
  await page.locator('body').press('ArrowRight');
  await page.locator('body').press('ArrowRight');
  await page.locator('body').press('ArrowRight');
  await page.locator('body').press('ArrowRight');
  await page.locator('body').press('ArrowRight');
  await page.locator('body').press('ArrowRight');
  await page.locator('body').press('ArrowRight');
  await page.locator('body').press('ArrowRight');
  await page.locator('body').press('ArrowRight');
  await page.locator('body').press('ArrowRight');
  await page.locator('body').press('ArrowRight');
  await page.locator('body').press('ArrowRight');
  await page.locator('body').press('ArrowRight');
  await page.getByRole('cell', { name: 'Sindhuja@yopmail.com' }).click();
  await page.locator('#pn_id_8').click();
  await page.locator('body').press('ArrowLeft');
  await page.locator('body').press('ArrowLeft');
  await page.locator('body').press('ArrowLeft');
  await page.locator('body').press('ArrowLeft');
  await page.locator('body').press('ArrowLeft');
  await page.locator('body').press('ArrowLeft');
  await page.locator('body').press('ArrowLeft');
  await page.locator('body').press('ArrowLeft');
  await page.locator('body').press('ArrowLeft');
  await page.getByText('Sindhuja Priya').click();
  await page.locator('.card.custom-background-card').first().click();
  await page.getByRole('img', { name: 'Onboarding Info', exact: true }).click();
  await page.locator('div:nth-child(2) > a').click();
  await page.locator('#pn_id_46').getByRole('button', { name: 'dropdown trigger' }).click();
  await page.getByRole('option', { name: 'Trainee Active' }).click();
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByText('Onboarding Information').click();
  await page.getByText('Employees').click();
  await page.getByRole('link', { name: 'Trainees (50)' }).click();
  await page.getByRole('searchbox', { name: 'Username' }).click();
  await page.getByRole('searchbox', { name: 'Username' }).fill('si');
  await page.getByRole('cell', { name: 'Sindhuja Priya' }).click();

}

import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://hrmsqarightlyhr.onpremise.cluster.rightlyhr.com/login');
  await page.getByText('Employees').click();
  await page.getByRole('link', { name: 'Trainees (52)' }).click();
  await page.getByText('Sindhuja Priya').click();
  await page.locator('div:nth-child(2) > a').click();
  await page.getByRole('textbox', { name: 'Please enter employee ID' }).click();
  await page.getByRole('textbox', { name: 'Please enter employee ID' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Please enter employee ID' }).fill('RHR234');
  await page.getByRole('combobox', { name: 'Please select marital status' }).click();
  await page.getByText('Single').click();
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByText('Basic information updated').click();
  await page.locator('div').filter({ hasText: /^Contact Info$/ }).nth(1).click();
  await page.locator('div:nth-child(2) > a').click();
  await page.getByRole('textbox', { name: 'Personal Email*' }).click();
  await page.getByRole('textbox', { name: 'Personal Email*' }).press('ControlOrMeta+C');
  await page.getByRole('textbox', { name: 'Work Mail*' }).click();
  await page.getByRole('textbox', { name: 'Work Mail*' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Work Mail*' }).fill('s');
  await page.getByRole('textbox', { name: 'Work Mail*' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Work Mail*' }).fill('S');
  await page.getByRole('textbox', { name: 'Work Mail*' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Work Mail*' }).fill('Sindhuja1@yopmail.com');
  await page.getByText('Contact InfoCloseSaveWork').click();
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByText('Contact Information updated').click();
  await page.getByText('Job').click();
  await page.locator('div').filter({ hasText: /^Job Info$/ }).nth(1).click();
  await page.locator('#pn_id_3').click();
  await page.locator('body').press('ArrowRight');
  await page.locator('body').press('ArrowRight');
  await page.locator('body').press('ArrowRight');
  await page.locator('body').press('ArrowRight');
  await page.locator('body').press('ArrowRight');
  await page.locator('body').press('ArrowRight');
  await page.locator('body').press('ArrowRight');
  await page.locator('body').press('ArrowRight');
  await page.locator('body').press('ArrowRight');
  await page.locator('body').press('ArrowRight');
  await page.locator('body').press('ArrowRight');
  await page.locator('body').press('ArrowRight');
  await page.locator('body').press('ArrowRight');
  await page.locator('body').press('ArrowRight');
  await page.locator('body').press('ArrowRight');
  await page.locator('body').press('ArrowRight');
  await page.locator('body').press('ArrowRight');
  await page.locator('body').press('ArrowRight');
  await page.locator('body').press('ArrowRight');
  await page.locator('body').press('ArrowRight');
  await page.locator('body').press('ArrowRight');
  await page.locator('body').press('ArrowRight');
  await page.locator('body').press('ArrowRight');
  await page.locator('body').press('ArrowRight');
  await page.locator('body').press('ArrowRight');
  await page.locator('body').press('ArrowRight');
  await page.locator('body').press('ArrowRight');
  await page.locator('body').press('ArrowRight');
  await page.locator('body').press('ArrowRight');
  await page.locator('body').press('ArrowRight');
  await page.locator('body').press('ArrowRight');
  await page.locator('i').nth(2).click();
  await page.getByText('Update').click();
  await page.getByRole('combobox', { name: 'Please select department' }).click();
  await page.getByRole('option', { name: 'SDF' }).click();
  await page.getByRole('combobox', { name: 'Please select team' }).click();
  await page.getByRole('option', { name: 'My team', exact: true }).click();
  await page.getByRole('combobox', { name: 'Please select shift' }).click();
  await page.getByText('General Shift').click();
  await page.locator('#pn_id_37 > .p-select-dropdown').click();
  await page.locator('#pn_id_37_1').click();
  await page.locator('#pn_id_37 > .p-select-dropdown').click();
  await page.getByRole('option', { name: 'Intern' }).click();
  await page.getByText('Effective Date*Job Role*Front').click();
  await page.getByRole('button', { name: 'Update' }).click();
  await page.locator('div').filter({ hasText: /^Trainee Onboard Request$/ }).nth(1).click();
  await page.getByText('Trainee Onboarding VerificationRequest For Onboard').click();
  await page1.goto('https://hrmsqarightlyhr.onpremise.cluster.rightlyhr.com/personalinfo/job/trainee-onboarding-requests');
  await page1.locator('rect').first().click();
  await page1.getByRole('button', { name: 'Icon Employee Fields Define' }).click();
  await page1.getByText('JobThis section is used to').click();
  await page1.getByRole('link', { name: 'Serving period' }).click();
  await page1.getByRole('cell', { name: 'Button Before Onboard' }).click();
  await page1.getByRole('cell', { name: '50' }).click();
  await page1.locator('tr:nth-child(3) > .text-center > .dropdown > span > .bi').click();
  await page1.locator('tr:nth-child(3) > .text-center > .dropdown > span > .bi').click();
  await page1.getByRole('cell').filter({ hasText: 'Update Delete' }).nth(2).click();
  await page1.getByText('Update').nth(2).click();
  await page1.locator('div').filter({ hasText: 'Serving Period Type *' }).nth(4).click();
  await page1.locator('div').filter({ hasText: 'Duration *' }).nth(4).click();
  await page1.getByRole('button', { name: 'Update' }).click();
  await page1.getByText('Serving Period updated').click();
  await page.getByText('Request For Onboard').click();
  await page.getByText('Onboarding request submitted').click();
  await page.getByRole('cell', { name: 'Waiting for Approval' }).click();
  await page.locator('#pn_id_5').click();
  await page2.getByText('Sindhuja Priya Trainee').click();
  await page2.getByRole('heading', { name: 'Sindhuja Priya Trainee', description: 'Sindhuja Priya Trainee Onboard Request Initiated' }).click();
  await page2.getByRole('table').first().click();
  const page3Promise = page2.waitForEvent('popup');
  await page2.getByRole('link', { name: 'Click here' }).click();
  const page3 = await page3Promise;
  await page3.getByText('Onboarding(6)').click();
  await page3.getByText('Trainees(4)').click();
  await page3.getByRole('cell', { name: 'Sindhuja Priya' }).click();
  await page3.getByRole('cell').filter({ hasText: 'ApproveReject' }).nth(2).click();
  await page3.getByText('Reject').nth(2).click();
  await page3.getByText('Are you sure you want to').click();
  await page3.getByText('Extend').click();
  await page3.getByText('Extend Discontinue Extend').click();
  await page3.getByRole('textbox', { name: 'Default select example' }).fill('2026-11-04');
  await page3.getByRole('textbox', { name: 'Feedback for Extend *' }).click();
  await page3.getByRole('textbox', { name: 'Feedback for Extend *' }).press('CapsLock');
  await page3.getByRole('textbox', { name: 'Feedback for Extend *' }).fill('E');
  await page3.getByRole('textbox', { name: 'Feedback for Extend *' }).press('CapsLock');
  await page3.getByRole('textbox', { name: 'Feedback for Extend *' }).fill('Extended by a month');
  await page3.getByRole('textbox', { name: 'Feedback for Extend *' }).click();
  await page3.getByRole('button', { name: 'Reject', exact: true }).click();
  await page3.getByText('Trainee request extend').click();
  await page2.getByTestId('virtuoso-item-list').getByText('Sindhuja Priya Trainee Onboard Period Extended').click();
  await page2.getByRole('heading', { name: 'Sindhuja Priya Trainee', description: 'Sindhuja Priya Trainee Onboard Period Extended' }).click();
  await page2.getByRole('cell', { name: 'Dear Sindhuja Priya, Greetings from RightlyHR! Your trainee onboarding period, which started on 03-Sep-2026 has been extended based on the feedback provided by your Manager, Bhavitha Reddy. Please log in to the portal and view the request status. Click here Best regards, RightlyHR', exact: true }).click();
  await page4.locator('#refresh').click();
  await page4.locator('iframe[name="ifmail"]').contentFrame().getByText('Sindhuja Priya Trainee').click();
  await page4.getByText('sindhuja@yopmail.com').click();
  await page4.locator('iframe[name="ifmail"]').contentFrame().getByText('Sindhuja Priya Trainee').click();
  await page4.locator('iframe[name="ifmail"]').contentFrame().getByRole('cell', { name: 'Dear Sindhuja Priya, Greetings from RightlyHR! Your trainee onboarding period, which started on 03-Sep-2026 has been extended based on the feedback provided by your Manager, Bhavitha Reddy. Please log in to the portal and view the request status. Click here Best regards, RightlyHR', exact: true }).click();
  await page.goto('https://hrmsqarightlyhr.onpremise.cluster.rightlyhr.com/personalinfo/personal/contact-details');
  await page.getByText('Job').click();
  await page.locator('div').filter({ hasText: /^Trainee Onboard Request$/ }).nth(1).click();
  await page.locator('#pn_id_1').click();
  await page.getByRole('cell', { name: 'Extended' }).click();
  await page.locator('body').press('ArrowRight');
  await page.locator('body').press('ArrowRight');
  await page.locator('body').press('ArrowRight');
  await page.locator('body').press('ArrowRight');
  await page.locator('body').press('ArrowRight');
  await page.locator('body').press('ArrowRight');
  await page.locator('body').press('ArrowRight');
  await page.locator('body').press('ArrowRight');
  await page.locator('app-info-icon > svg > path').first().click();
  await page2.goto('https://outlook.cloud.microsoft/mail/AAMkAGNjYzk0ZjU0LWUzNzgtNGM0Ni04MDQ3LTViZWMyMDc5YjA4ZgAuAAAAAADgcVSEDV5BQ56DJUznlInnAQCEnI5FQHKjTI4ZPGXTIV7aAACWc3M%2FAAA%3D');
  await page2.getByLabel('Unread Test Snad Sindhuja Priya Trainee Onboard Request Initiated 5:35 PM Dear').getByText('Sindhuja Priya Trainee').click();
  await page2.getByRole('heading', { name: 'Sindhuja Priya Trainee', description: 'Sindhuja Priya Trainee Onboard Request Initiated' }).click();
  await page2.getByRole('cell', { name: 'Dear Bhavitha Reddy, Greetings from RightlyHR! A trainee onboard request has been raised for Sindhuja Priya. Your review and confirmation as the Manager are required to proceed with the onboarding process. Kindly take a moment to review and approve the request at your earliest convenience. Please log in to the portal and view the request status. Click here Best regards, RightlyHR', exact: true }).click();
  await page3.locator('tr:nth-child(4) > td:nth-child(6) > .dropdown > span > .bi').click();
  await page3.locator('div').filter({ hasText: /^ApproveReject$/ }).nth(2).click();
  await page3.getByText('Approve').nth(3).click();
  await page3.getByText('Are you sure you want to').click();
  await page3.getByRole('button', { name: 'Approved' }).click();
  await page3.getByRole('button', { name: 'Approve', exact: true }).click();
  await page3.getByText('Request has been approved').click();
  await page3.locator('tr:nth-child(4) > td:nth-child(5) > div > .bi').click();
  await page3.getByText('Comments: ApprovedCommented').first().click();
  await page3.getByText('Comments: ApprovedCommented').nth(1).click();
  await page3.locator('div:nth-child(2) > a').click();
  await page3.locator('tr:nth-child(4) > td:nth-child(6) > .dropdown').click();
  await page3.getByText('Reject').nth(3).click();
  await page3.getByRole('button', { name: 'Close' }).click();
  await page3.locator('tr:nth-child(4) > td:nth-child(6) > .dropdown').click();
  await page3.getByText('Process').nth(1).click();
  await page3.getByText('Trainee request processed').click();
  await page2.getByText('Sindhuja Priya Trainee Onboard Confirmed by Bhavitha Reddy').click();
  await page2.getByRole('cell', { name: 'Company Logo Image Dear' }).nth(1).click();
  await page4.locator('iframe[name="ifmail"]').contentFrame().getByText('Sindhuja Priya Trainee').click();
  await page4.locator('iframe[name="ifmail"]').contentFrame().getByRole('cell', { name: 'Dear Sindhuja Priya, Greetings from RightlyHR! We are pleased to inform you that you have successfully completed your trainee onboarding process. Your employment status has now been officially confirmed. Congratulations on this milestone! We truly appreciate your efforts and look forward to your continued success with the team. Please log in to the portal and view the request status. Click here Best regards, RightlyHR', exact: true }).click();
  await page.goto('https://hrmsqarightlyhr.onpremise.cluster.rightlyhr.com/personalinfo/job/trainee-onboarding-requests');
  await page.getByRole('row', { name: 'Sep 3, 2026 Sep 3, 2026 Nov 4, 2026 - Processed ' }).locator('i').click();
  await page.getByRole('cell').filter({ hasText: 'Ready for Onboard' }).click();
  await page.getByText('Ready for Onboard').click();
  await page.getByText('Are you sure you want to').click();
  await page.getByRole('button', { name: 'Yes' }).click();
  await page.getByText('Employee onboarded').click();
  await page.getByText('Employees').click();
  await page.getByText('Active(190)').click();
  await page.getByRole('link', { name: 'Trainees (52)' }).click();
  await page.getByRole('searchbox', { name: 'Username' }).click();
  await page.getByRole('searchbox', { name: 'Username' }).fill('sindh');
  await page.goto('https://hrmsqarightlyhr.onpremise.cluster.rightlyhr.com/employee-management/active/interns');
  await page.getByRole('searchbox', { name: 'Username' }).click();
  await page.getByRole('searchbox', { name: 'Username' }).fill('sindh');
  await page.getByText('Employees', { exact: true }).click();
  await page.getByRole('button', { name: 'Generate Documents' }).click();
  await page.locator('div').filter({ hasText: /^Offer Letter$/ }).first().click();
  await page.getByRole('combobox', { name: 'Please select employee' }).click();
  await page.getByRole('searchbox', { name: 'Search employee' }).fill('sin');
  await page.getByRole('option', { name: '- Sindhuja Priya' }).click();
});

);

