import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
    await page.goto('https://hrmsqarightlyhr.onpremise.cluster.rightlyhr.com/login');
    await page.getByRole('textbox', { name: 'Please enter email' }).click();
    await page.getByRole('textbox', { name: 'Please enter email' }).fill('bhavitha.palagiri@snaddevelopers.com');
    await page.getByRole('textbox', { name: 'Please enter password' }).click();
    await page.getByRole('textbox', { name: 'Please enter password' }).press('CapsLock');
    await page.getByRole('textbox', { name: 'Please enter password' }).fill('B');
    await page.getByRole('textbox', { name: 'Please enter password' }).press('CapsLock');
    await page.getByRole('textbox', { name: 'Please enter password' }).fill('Bhavi@16');
    await page.getByRole('button', { name: 'Login' }).click();
    await page.goto('https://hrmsqarightlyhr.onpremise.cluster.rightlyhr.com/dashboard/emp');
    await page.getByText('Employees').click();
    await page.getByText('Prospective').click();
    await page.getByRole('link', { name: 'Employees (630)' }).click();
    await page.getByRole('button', { name: 'Add Prospective Employee' }).click();
    await page.getByRole('textbox', { name: 'Please enter first name' }).click();
    await page.getByRole('textbox', { name: 'Please enter first name' }).press('CapsLock');
    await page.getByRole('textbox', { name: 'Please enter first name' }).fill('M');
    await page.getByRole('textbox', { name: 'Please enter first name' }).press('CapsLock');
    await page.getByRole('textbox', { name: 'Please enter first name' }).fill('Murali');
    await page.getByRole('textbox', { name: 'Please enter last name' }).click();
    await page.getByRole('textbox', { name: 'Please enter last name' }).press('CapsLock');
    await page.getByRole('textbox', { name: 'Please enter last name' }).fill('R');
    await page.getByRole('textbox', { name: 'Please enter last name' }).press('CapsLock');
    await page.getByRole('textbox', { name: 'Please enter last name' }).fill('Raj');
    await page.getByRole('textbox', { name: 'Please enter personal email ID' }).click();
    await page.getByRole('textbox', { name: 'Please enter personal email ID' }).press('CapsLock');
    await page.getByRole('textbox', { name: 'Please enter personal email ID' }).fill('M');
    await page.getByRole('textbox', { name: 'Please enter personal email ID' }).press('CapsLock');
    await page.getByRole('textbox', { name: 'Please enter personal email ID' }).fill('Murali');
    await page.getByRole('textbox', { name: 'Please enter personal email ID' }).press('CapsLock');
    await page.getByRole('textbox', { name: 'Please enter personal email ID' }).fill('MuraliR');
    await page.getByRole('textbox', { name: 'Please enter personal email ID' }).press('CapsLock');
    await page.getByRole('textbox', { name: 'Please enter personal email ID' }).fill('MuraliRaj@yopmail.com');
    await page.getByRole('textbox', { name: 'Please enter personal email ID' }).click();
    await page.getByRole('textbox', { name: 'Please enter personal email ID' }).click();
    await page.getByRole('textbox', { name: 'Please enter personal email ID' }).press('ArrowLeft');
    await page.getByRole('textbox', { name: 'Please enter personal email ID' }).press('ArrowLeft');
    await page.getByRole('textbox', { name: 'Please enter personal email ID' }).press('ArrowLeft');
    await page.getByRole('textbox', { name: 'Please enter personal email ID' }).press('ArrowLeft');
    await page.getByRole('textbox', { name: 'Please enter personal email ID' }).press('ArrowLeft');
    await page.getByRole('textbox', { name: 'Please enter personal email ID' }).press('ArrowLeft');
    await page.getByRole('textbox', { name: 'Please enter personal email ID' }).press('ArrowLeft');
    await page.getByRole('textbox', { name: 'Please enter personal email ID' }).press('ArrowLeft');
    await page.getByRole('textbox', { name: 'Please enter personal email ID' }).press('ArrowLeft');
    await page.getByRole('textbox', { name: 'Please enter personal email ID' }).press('ArrowLeft');
    await page.getByRole('textbox', { name: 'Please enter personal email ID' }).fill('Muraliraj@yopmail.com');
    await page.getByRole('combobox', { name: 'Please select designation' }).click();
    await page.getByRole('searchbox').fill('fr');
    await page.getByRole('option', { name: 'Front End Developer' }).click();
    await page.getByRole('combobox', { name: 'Please select employment type' }).click();
    await page.getByRole('option', { name: 'Fresher' }).click();
    await page.getByRole('combobox', { name: 'Please select location' }).click();
    await page.getByRole('option', { name: 'Hyderabad' }).click();
    await page.locator('#sublocation').getByRole('button', { name: 'dropdown trigger' }).click();
    await page.getByRole('option', { name: 'Jai Hind Enclave building' }).click();
    await page.getByRole('button', { name: 'Add' }).click();
    await page.getByText('Prospective employee created').click();
    await page.getByRole('searchbox', { name: 'Username' }).click();
    await page.getByRole('searchbox', { name: 'Username' }).fill('murali');
    await page.getByRole('searchbox', { name: 'Username' }).press('ArrowRight');
    await page.getByRole('searchbox', { name: 'Username' }).press('ArrowRight');
    await page.getByRole('cell', { name: 'Murali Raj' }).click();
    await page.locator('body').press('ArrowRight');
    await page.getByRole('button', { name: 'Request for Documents' }).click();
    await page.getByText('Email has been sent').click();
    await page1.goto('https://www.google.com/sorry/index?continue=https://www.google.com/search%3Fq%3Dyopmail%26oq%3Dyopmail%26gs_lcrp%3DEgZjaHJvbWUyBggAEEUYOdIBCDMwOTVqMGo3qAIAsAIA%26sourceid%3Dchrome%26source%3Dchrome.ob%26ie%3DUTF-8%26sei%3DD_qfav7AGqyahvcPr4Cl4Qo&q=EgQx-QtmGI_0_9QGIjC3UUPq4DyYGxrm31CxnRdRkbGapMXWdZ5fblawTMR3KguFILCpinSpkSW7vJnljjUyAVJaAUM');
    await page1.locator('iframe[name="a-52dbaso0cru5"]').contentFrame().getByRole('checkbox', { name: 'I\'m not a robot' }).click();
    await page2.goto('https://www.google.com/sorry/index?continue=https://www.google.com/search%3Fq%3Dyopmail%26oq%3Dyopmail%26gs_lcrp%3DEgZjaHJvbWUyBggAEEUYOdIBCDI4MDZqMGo3qAIAsAIA%26sourceid%3Dchrome%26source%3Dchrome.ob%26ie%3DUTF-8%26sei%3DGvqfasKPC-yRnesPwuXssAg&q=EgQx-QtmGJr0_9QGIjBzch5XFHs75ECSRc1Sb1IZHTpwkDtoB-YQm-7jGNf65QbYyLYKt7kux0-xP2gBZgkyAVJaAUM');
    await page2.locator('iframe[name="a-htidas2kptjv"]').contentFrame().getByRole('checkbox', { name: 'I\'m not a robot' }).click();
    await page2.locator('iframe[name="c-htidas2kptjv"]').contentFrame().locator('[id="10"]').click();
    await page2.locator('iframe[name="c-htidas2kptjv"]').contentFrame().locator('[id="11"]').click();
    await page2.locator('iframe[name="c-htidas2kptjv"]').contentFrame().locator('[id="6"]').click();
    await page2.locator('iframe[name="c-htidas2kptjv"]').contentFrame().locator('[id="7"]').click();
    await page2.locator('iframe[name="c-htidas2kptjv"]').contentFrame().locator('[id="14"]').click();
    await page2.locator('iframe[name="c-htidas2kptjv"]').contentFrame().getByRole('button', { name: 'Verify' }).click();
    await page2.locator('iframe[name="c-htidas2kptjv"]').contentFrame().locator('[id="4"]').click();
    await page2.locator('iframe[name="c-htidas2kptjv"]').contentFrame().locator('[id="7"]').click();
    await page2.locator('iframe[name="c-htidas2kptjv"]').contentFrame().locator('[id="1"]').click();
    await page2.locator('iframe[name="c-htidas2kptjv"]').contentFrame().getByRole('button', { name: 'Verify' }).click();
    await page2.getByRole('link', { name: 'YOPmail - Disposable Email Address - Anonymous and ... YOPmail https://yopmail.' }).click();
    await page2.getByRole('textbox', { name: 'Login' }).click();
    await page2.getByRole('textbox', { name: 'Login' }).fill('muraliraj');
    await page2.getByRole('textbox', { name: 'Login' }).press('Enter');
    await page2.getByTitle('Check Inbox @yopmail.com').click();
    await page2.locator('iframe[name="ifmail"]').contentFrame().locator('iframe[name="a-ypajjumvzit9"]').contentFrame().getByRole('checkbox', { name: 'I\'m not a robot' }).click();
    await page2.locator('iframe[name="ifmail"]').contentFrame().locator('iframe[name="c-ypajjumvzit9"]').contentFrame().locator('[id="0"]').click();
    await page2.locator('iframe[name="ifmail"]').contentFrame().locator('iframe[name="c-ypajjumvzit9"]').contentFrame().locator('[id="5"]').click();
    await page2.locator('iframe[name="ifmail"]').contentFrame().locator('iframe[name="c-ypajjumvzit9"]').contentFrame().locator('[id="7"]').click();
    await page2.locator('iframe[name="ifmail"]').contentFrame().locator('iframe[name="c-ypajjumvzit9"]').contentFrame().getByRole('button', { name: 'Verify' }).click();
    const page3Promise = page2.waitForEvent('popup');
    await page2.locator('iframe[name="ifmail"]').contentFrame().getByRole('link', { name: 'Click here' }).click();
    const page3 = await page3Promise;
    await page3.getByRole('textbox', { name: 'Username*' }).click();
    await page3.getByRole('textbox', { name: 'Username*' }).fill('Muraliraj@yopmail.com');
    await page3.getByRole('textbox', { name: 'Password*' }).click();
    await page3.getByRole('textbox', { name: 'Password*' }).fill('8MdHCZ*G');
    await page3.getByRole('button', { name: 'Login' }).click();
    await page3.getByRole('button', { name: 'Go to Application' }).click();
    await page3.locator('#gender').getByRole('button', { name: 'dropdown trigger' }).click();
    await page3.getByRole('option', { name: 'Male', exact: true }).click();
    await page3.getByRole('combobox', { name: 'Please select salutation' }).click();
    await page3.getByRole('option', { name: 'Mr.' }).click();
    await page3.getByText('Select country').click();
    await page3.locator('lib-country-list').getByRole('textbox').fill('91');
    await page3.getByText('India (भारत)').click();
    await page3.getByRole('textbox', { name: 'Please enter your mobile' }).click();
    await page3.getByRole('textbox', { name: 'Please enter your mobile' }).fill('097567 47457');
    await page3.getByRole('textbox', { name: 'Date Of Birth *' }).fill('2026-09-15');
    await page3.getByText('Age should be between 18 and').click();
    await page3.getByRole('textbox', { name: 'Date Of Birth *' }).fill('1999-02-09');
    await page3.locator('#bloodGroup').getByRole('button', { name: 'dropdown trigger' }).click();
    await page3.getByRole('option', { name: 'A+' }).click();
    await page3.locator('#currentAddressLine1').click();
    await page3.locator('#currentAddressLine1').press('CapsLock');
    await page3.locator('#currentAddressLine1').fill('R');
    await page3.locator('#currentAddressLine1').press('CapsLock');
    await page3.locator('#currentAddressLine1').fill('Road no,02');
    await page3.locator('#currentCity').click();
    await page3.locator('#currentCity').press('CapsLock');
    await page3.locator('#currentCity').press('CapsLock');
    await page3.locator('#currentCity').press('CapsLock');
    await page3.locator('#currentCity').fill('H');
    await page3.locator('#currentCity').press('CapsLock');
    await page3.locator('#currentCity').fill('Hyderabad');
    await page3.locator('#currentCity').press('Tab');
    await page3.locator('#currentState').press('CapsLock');
    await page3.locator('#currentState').fill('T');
    await page3.locator('#currentState').press('CapsLock');
    await page3.locator('#currentState').fill('Telangana');
    await page3.getByRole('textbox', { name: 'Country*' }).click();
    await page3.getByRole('textbox', { name: 'Country*' }).press('CapsLock');
    await page3.getByRole('textbox', { name: 'Country*' }).fill('I');
    await page3.getByRole('textbox', { name: 'Country*' }).press('CapsLock');
    await page3.getByRole('textbox', { name: 'Country*' }).fill('India');
    await page3.locator('#currentzipCode').click();
    await page3.locator('#currentzipCode').fill('500013');
    await page3.getByRole('checkbox', { name: 'Same as Current Address' }).check();
    await page3.getByRole('button', { name: 'Next' }).click();
    await page3.getByRole('row', { name: 'Resume* - - - Requested' }).getByRole('button').click();
    await page3.getByRole('button', { name: 'Choose File' }).setInputFiles('Teja_1788787002103_AppointmentLetter_Unsigned.pdf');
    await page3.getByRole('button', { name: 'Upload' }).click();
    await page3.locator('div').filter({ hasText: 'Document uploaded successfully' }).nth(3).click();
    await page3.getByRole('row', { name: 'PAN* - - - Requested - - ' }).getByRole('button').click();
    await page3.getByRole('textbox', { name: 'Document Number*' }).click();
    await page3.getByRole('textbox', { name: 'Document Number*' }).fill('ry45645645');
    await page3.getByRole('button', { name: 'Choose File' }).setInputFiles('Mahesh__Yadav_1788346806139_OfferLetter.pdf');
    await page3.getByRole('button', { name: 'Upload' }).click();
    await page3.getByRole('row', { name: 'Aadhaar* - - - Requested' }).getByRole('button').click();
    await page3.getByRole('textbox', { name: 'Document Number*' }).click();
    await page3.getByRole('row', { name: 'Aadhaar* - - - Requested' }).getByRole('button').click();
    await page3.getByRole('textbox', { name: 'Document Number*' }).click();
    await page3.getByRole('textbox', { name: 'Document Number*' }).fill('456464565464');
    await page3.getByRole('button', { name: 'Choose File' }).setInputFiles('Mahesh__Yadav_1788346806139_OfferLetter.pdf');
    await page3.getByRole('button', { name: 'Upload' }).click();
    await page3.getByRole('button', { name: 'Submit' }).click();
    await page3.getByText('Are you sure you want to').click();
    await page3.getByRole('button', { name: 'Submit' }).click();
    await page3.getByText('Submitted successfully, We’ll').click();
}
import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
    await page.goto('https://hrmsqarightlyhr.onpremise.cluster.rightlyhr.com/login');
    await page.getByText('Employees').click();
    await page.getByRole('button', { name: 'Generate Documents' }).click();
    await page.locator('div').filter({ hasText: /^Offer Letter$/ }).first().click();
    await page.locator('#pn_id_7').getByRole('button', { name: 'dropdown trigger' }).click();
    await page.locator('#pn_id_7').getByRole('button', { name: 'dropdown trigger' }).click();
    await page.getByRole('searchbox', { name: 'Search employee' }).fill('');
    await page.getByRole('option', { name: '- Arjun Menon' }).click();
    await page.getByRole('combobox', { name: 'Please select address' }).click();
    await page.getByRole('option', { name: 'Current Address' }).click();
    await page.locator('#pn_id_17').getByRole('combobox', { name: 'No' }).click();
    await page.getByText('Select Employee*12908 - Arjun MenonPersonal Email ID*Salutation*Mr.First Name*').click();
    await page.getByRole('spinbutton', { name: 'Please enter salary' }).click();
    await page.getByRole('spinbutton', { name: 'Please enter salary' }).fill('400000');
    await page.getByRole('combobox', { name: 'Please select variable pay' }).click();
    await page.getByRole('option', { name: 'No' }).click();
    await page.getByPlaceholder('Please enter offer issued date').fill('2026-09-08');
    await page.getByPlaceholder('Please enter expected start').fill('2026-09-08');
    await page.getByPlaceholder('Please enter offer expiry date').fill('2026-09-08');
    await page.getByRole('combobox', { name: 'Please select document type' }).click();
    await page.getByText('Soft Copy').click();
    await page.getByRole('combobox', { name: 'Please select signature' }).click();
    await page.getByText('saii Pavan Dinesh Tejaa').click();
    const downloadPromise = page.waitForEvent('download');
    await page.getByRole('button', { name: 'Generate Offer Letter' }).click();
    const download = await downloadPromise;
    await page.getByText('Offer letter generated').click();
    await page.getByRole('button', { name: 'Request For Approval' }).click();
    await page.getByText('Approval request sent').click();
    await page.goto('https://hrmsqarightlyhr.onpremise.cluster.rightlyhr.com/pending-approvals/on-boarding/offer-letter-history');
    await page1.goto('https://www.google.com/sorry/index?continue=https://www.google.com/search%3Fq%3Dyopmail%26oq%3Dyopmail%26gs_lcrp%3DEgZjaHJvbWUyBggAEEUYOdIBCDE1OThqMGo3qAIAsAIB%26sourceid%3Dchrome%26source%3Dchrome.ob%26ie%3DUTF-8%26sei%3DNB6gaoSzO4efhvcP6P_q8Ac&q=EgQx-QtmGLW8gNUGIjA6hrce9JKWAAKC1R3MDp7tm79aScaqL2Kuo7sZdRi6HKRrky7DUt8wKiFB6rtwSW0yAVJaAUM');
    await page1.locator('iframe[name="a-gx1bm3hgsu9c"]').contentFrame().getByRole('checkbox', { name: 'I\'m not a robot' }).click();
    await page1.getByTitle('Check Inbox @yopmail.com').click();
    await page1.locator('iframe[name="ifmail"]').contentFrame().locator('iframe[name="a-z1wbqfgk5zlo"]').contentFrame().getByRole('checkbox', { name: 'I\'m not a robot' }).click();
    const page2Promise = page1.waitForEvent('popup');
    await page1.locator('iframe[name="ifmail"]').contentFrame().getByRole('link', { name: 'Click here' }).click();
    const page2 = await page2Promise;
    await page2.getByRole('textbox', { name: 'Username*' }).click();
    await page2.getByRole('textbox', { name: 'Username*' }).fill('arjun.menon4584@yopmail.com');
    await page2.getByRole('textbox', { name: 'Password*' }).click();
    await page2.getByRole('textbox', { name: 'Password*' }).fill('4Kn4c0b*');
    await page2.getByRole('button', { name: 'Login' }).click();
    await page2.getByRole('button', { name: 'Go to Application' }).click();
    await page2.getByRole('button', { name: 'Next' }).click();
    await page2.getByRole('button', { name: 'Next' }).click();
    await page2.getByRole('button', { name: 'Accept' }).click();
    await page2.getByRole('button', { name: 'Yes' }).click();
    await page2.getByText('Offer letter accepted').click();
    await page2.getByRole('button', { name: 'Next' }).click();
    await page2.getByRole('button', { name: 'Add' }).click();
    await page2.getByRole('button', { name: 'dropdown trigger' }).click();
    await page2.getByRole('option', { name: 'B.TECH' }).click();
    await page2.getByRole('textbox', { name: 'University*' }).click();
    await page2.getByRole('textbox', { name: 'University*' }).press('CapsLock');
    await page2.getByRole('textbox', { name: 'University*' }).fill('T');
    await page2.getByRole('textbox', { name: 'University*' }).press('CapsLock');
    await page2.getByRole('textbox', { name: 'University*' }).fill('Test');
    await page2.getByRole('textbox', { name: 'Specialization*' }).click();
    await page2.getByRole('textbox', { name: 'Specialization*' }).press('CapsLock');
    await page2.getByRole('textbox', { name: 'Specialization*' }).fill('CSE');
    await page2.getByRole('spinbutton', { name: 'GPA*' }).click();
    await page2.getByRole('spinbutton', { name: 'GPA*' }).fill('8');
    await page2.getByRole('textbox', { name: 'Start Date*' }).fill('2020-06-09');
    await page2.getByRole('textbox', { name: 'To Date*' }).fill('2023-06-06');
    await page2.getByRole('button', { name: 'Attachment (Upload the Image' }).setInputFiles('Teja_1788786876319_AppointmentLetter_Unsigned.pdf');
    await page2.getByRole('button', { name: 'Add' }).click();
    await page2.getByText('Academic record added').click();
    await page2.getByRole('button', { name: 'Next' }).click();
    await page2.getByRole('textbox', { name: 'Please enter name' }).first().click();
    await page2.getByRole('textbox', { name: 'Please enter name' }).first().press('CapsLock');
    await page2.getByRole('textbox', { name: 'Please enter name' }).first().fill('s');
    await page2.getByRole('textbox', { name: 'Please enter name' }).first().press('CapsLock');
    await page2.getByRole('textbox', { name: 'Please enter name' }).first().fill('sREE');
    await page2.getByRole('textbox', { name: 'Please enter name' }).first().press('Tab');
    await page2.getByRole('textbox', { name: 'Please enter personal email ID' }).first().fill('S');
    await page2.getByRole('textbox', { name: 'Please enter personal email ID' }).first().press('CapsLock');
    await page2.getByRole('textbox', { name: 'Please enter personal email ID' }).first().fill('Sree@yopmail.com');
    await page2.getByText('Select country').first().click();
    await page2.getByRole('textbox').nth(2).fill('91');
    await page2.getByRole('listbox').getByText('India (भारत)').click();
    await page2.getByRole('listbox').getByText('Bolivia (Plurinational State').click();
    await page2.getByRole('spinbutton', { name: 'Please enter mobile number' }).first().fill('6775674644');
    await page2.getByRole('textbox', { name: 'Please enter name' }).nth(1).press('CapsLock');
    await page2.getByRole('textbox', { name: 'Please enter name' }).nth(1).fill('T');
    await page2.getByRole('textbox', { name: 'Please enter name' }).nth(1).press('CapsLock');
    await page2.getByRole('textbox', { name: 'Please enter name' }).nth(1).fill('Tulasi');
    await page2.getByRole('textbox', { name: 'Please enter name' }).nth(1).press('Tab');
    await page2.getByRole('textbox', { name: 'Please enter personal email ID' }).nth(1).press('CapsLock');
    await page2.getByRole('textbox', { name: 'Please enter personal email ID' }).nth(1).fill('T');
    await page2.getByRole('textbox', { name: 'Please enter personal email ID' }).nth(1).press('CapsLock');
    await page2.getByRole('textbox', { name: 'Please enter personal email ID' }).nth(1).fill('Tulasi@yopmail.com');
    await page2.getByText('+591').nth(1).click();
    await page2.locator('lib-country-list').filter({ hasText: '+591Afghanistan' }).getByRole('textbox').fill('91');
    await page2.getByRole('listbox').getByText('India (भारत)').click();
    await page2.getByRole('spinbutton', { name: 'Please enter mobile number' }).nth(1).click();
    await page2.getByRole('spinbutton', { name: 'Please enter mobile number' }).nth(1).fill('8567567566');
    await page2.getByRole('combobox', { name: 'Please select relation' }).click();
    await page2.getByRole('option', { name: 'Mother' }).click();
    await page2.getByText('Name*Personal Email IDMobile').nth(1).click();
    await page2.getByRole('button', { name: 'Next' }).click();
    await page2.getByRole('button', { name: 'Skip & continue' }).click();
    await page2.getByRole('button', { name: 'Submit' }).click();
    await page2.getByText('Are you sure you want to').click();
    await page2.getByRole('button', { name: 'Yes' }).click();
    await page2.getByRole('button', { name: 'Close' }).click();
    await page.goto('https://hrmsqarightlyhr.onpremise.cluster.rightlyhr.com/employee-management/prospective/employees');
    await page.getByRole('searchbox', { name: 'Username' }).fill('arjun');
    await page.goto('https://hrmsqarightlyhr.onpremise.cluster.rightlyhr.com/employee-management/prospective/employees');
    await page.getByRole('searchbox', { name: 'Username' }).fill('arjun');
    await page.goto('https://hrmsqarightlyhr.onpremise.cluster.rightlyhr.com/employee-management/active/employees');
    await page.getByRole('searchbox', { name: 'Username' }).click();
    await page.getByRole('searchbox', { name: 'Username' }).fill('arjun');
    await page.getByText('Probation(63)').click();
    await page.getByRole('searchbox', { name: 'Username' }).click();
    await page.getByRole('searchbox', { name: 'Username' }).fill('arju');
    await page.getByText('Arjun Menon').click();
    await page.locator('.ng-star-inserted > a').click();
    await page.getByRole('textbox', { name: 'Please enter employee ID' }).click();
    await page.getByRole('textbox', { name: 'Please enter employee ID' }).press('CapsLock');
    await page.getByRole('textbox', { name: 'Please enter employee ID' }).fill('RHR');
    await page.getByRole('textbox', { name: 'Please enter employee ID' }).press('CapsLock');
    await page.getByRole('textbox', { name: 'Please enter employee ID' }).fill('RHR123');
    await page.getByRole('combobox', { name: 'Please select marital status' }).click();
    await page.getByRole('option', { name: 'Single' }).click();
    await page.getByRole('button', { name: 'Save' }).click();
    await page.getByRole('textbox', { name: 'Please enter employee ID' }).click();
    await page.getByRole('textbox', { name: 'Please enter employee ID' }).fill('RHR1233');
    await page.getByRole('button', { name: 'Save' }).click();
    await page.getByText('Basic information updated').click();
    await page.locator('div').filter({ hasText: /^Contact Info$/ }).nth(1).click();
    await page.locator('.ng-star-inserted > a').click();
    await page.getByRole('textbox', { name: 'Personal Email*' }).dblclick();
    await page.getByRole('textbox', { name: 'Personal Email*' }).click();
    await page.getByRole('textbox', { name: 'Personal Email*' }).click();
    await page.getByRole('textbox', { name: 'Work Mail*' }).click();
    await page.getByRole('textbox', { name: 'Work Mail*' }).fill('arjun123@yopmail.com');
    await page.getByRole('button', { name: 'Save' }).click();
    await page.getByText('Contact Information updated').click();
    await page.getByText('Job').click();
    await page.getByRole('img', { name: 'Job Info' }).click();
    await page.getByRole('cell', { name: '-' }).nth(2).click();
    await page.locator('body').press('ArrowRight');
    await page.locator('body').press('ArrowRight');
    await page.locator('body').press('ArrowRight');
    await page.locator('body').press('ArrowRight');
    await page.locator('body').press('ArrowRight');
    await page.locator('body').press('ArrowRight');
    await page.locator('body').press('ArrowRight');
    await page.locator('body').press('ArrowRight');
    await page.locator('body').press('ArrowRight');
    await page.locator('body').press('ArrowRight');
    await page.locator('body').press('ArrowRight');
    await page.locator('body').press('ArrowRight');
    await page.locator('body').press('ArrowRight');
    await page.locator('body').press('ArrowRight');
    await page.locator('body').press('ArrowRight');
    await page.locator('body').press('ArrowRight');
    await page.locator('body').press('ArrowRight');
    await page.locator('body').press('ArrowRight');
    await page.locator('body').press('ArrowRight');
    await page.locator('body').press('ArrowRight');
    await page.locator('body').press('ArrowRight');
    await page.locator('body').press('ArrowRight');
    await page.locator('body').press('ArrowRight');
    await page.locator('body').press('ArrowRight');
    await page.locator('body').press('ArrowRight');
    await page.locator('body').press('ArrowRight');
    await page.locator('body').press('ArrowRight');
    await page.locator('body').press('ArrowRight');
    await page.locator('i').nth(2).click();
    await page.locator('#pn_id_4').click();
    await page.locator('i').nth(2).click();
    await page.locator('#pn_id_4').click();
    await page.getByRole('cell').filter({ hasText: 'UpdateDelete Separation' }).click();
    await page.getByText('Update').click();
    await page.getByRole('combobox', { name: 'Please select department' }).click();
    await page.getByText('SDF').click();
    await page.getByRole('combobox', { name: 'Please select team' }).click();
    await page.getByRole('option', { name: 'My team', exact: true }).click();
    await page.getByRole('combobox', { name: 'Please select Reporting' }).click();
    await page.getByRole('searchbox').fill('bhav');
    await page.getByRole('option', { name: 'SD3021300 - Bhavitha Reddy' }).click();
    await page.getByRole('combobox', { name: 'Please select shift' }).click();
    await page.getByRole('option', { name: 'General Shift' }).click();
    await page.getByRole('combobox', { name: 'Please select job type' }).click();
    await page.locator('#pn_id_32_1').click();
    await page.getByRole('button', { name: 'Update' }).click();
    await page.getByText('Job details updated').click();
});