import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://hrmsqarightlyhr.onpremise.cluster.rightlyhr.com/login');
  await page.getByRole('textbox', { name: 'Please enter email' }).click();
  await page.getByRole('textbox', { name: 'Please enter email' }).fill('pavan.nedunuri@snaddevelopers.com');
  await page.getByRole('textbox', { name: 'Please enter password' }).click();
  await page.getByRole('textbox', { name: 'Please enter password' }).fill('Pavan@123');
  await page.locator('i').click();
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByText('Employees').click();
  await page.getByText('Probation(64)').click();
  await page.getByRole('searchbox', { name: 'Username' }).click();
  await page.getByRole('searchbox', { name: 'Username' }).fill('bhav');
  await page.getByText('Bhavitha Reddy').click();
  await page.getByText('Job').click();
  await page.locator('div').filter({ hasText: /^Probation Info$/ }).first().click();
  await page.getByRole('columnheader', { name: 'Applied Date' }).click();
  await page.getByRole('columnheader', { name: 'Probation Period(In days)' }).click();
  await page.getByRole('columnheader', { name: 'Probation start date' }).click();
  await page.getByRole('columnheader', { name: 'Probation end date' }).click();
  await page.getByRole('columnheader', { name: 'Probation extended date' }).click();
  await page.getByRole('columnheader', { name: 'Approver History' }).click();
  await page.getByRole('columnheader', { name: 'Action(s)' }).click();
  await page.getByRole('columnheader', { name: 'status' }).click();
  await page.getByRole('cell', { name: 'Feb 20,' }).first().click();
  await page.getByRole('cell', { name: '50' }).click();
  await page.getByRole('cell', { name: 'Feb 20,' }).nth(1).click();
  await page.getByRole('cell', { name: 'Apr 11,' }).click();
  await page.getByRole('cell', { name: '-' }).first().click();
  await page.locator('div').filter({ hasText: /^-$/ }).click();
  await page.getByRole('cell', { name: 'Pending' }).click();
  await page.getByRole('cell').filter({ hasText: 'Request for Probation' }).click();
  await page.locator('.show').first().click();
  await page.locator('.show').first().click();
  await page.locator('.dropdown > a').click();
  await page.getByRole('cell', { name: '  Request for Probation' }).getByRole('list').click();
  await page.getByText('Probation request raised').click();
  await page.getByText('Pending Approvals').click();
  await page.locator('div').filter({ hasText: /^Onboarding\(5\)$/ }).first().click();
  await page.getByText('Probation(1)').click();
  await page.locator('#pn_id_7').click();
  await page.getByRole('columnheader', { name: 'Employee ID' }).click();
  await page.getByRole('columnheader', { name: 'Employee Name' }).click();
  await page.getByRole('columnheader', { name: 'Probation Start Date' }).click();
  await page.getByRole('columnheader', { name: 'Approved History' }).click();
  await page.getByRole('columnheader', { name: 'Action' }).click();
  await page.getByRole('cell', { name: 'SD3021300' }).click();
  await page.getByRole('cell', { name: 'Bhavitha Reddy' }).click();
  await page.getByRole('cell', { name: 'Apr 11,' }).click();
  await page.getByRole('cell', { name: '-' }).click();
  await page.getByRole('button', { name: 'Assessment form' }).click();
  await page.getByText('ASSESSMENT FORM FOR PROBATION CONFIRMATIONEmp.ID:SD3021300Emp.Name:Bhavitha').click();
  await page.locator('div').filter({ hasText: /^OutStanding$/ }).nth(3).click();
  await page.locator('#checkformheader').first().check();
  await page.locator('div:nth-child(2) > .row > div:nth-child(7) > div > .ng-star-inserted > .d-flex').click();
  await page.locator('div:nth-child(2) > .row > div:nth-child(7) > div > .ng-star-inserted > .d-flex > #checkformheader').check();
  await page.getByText('ASSESSMENT FORM FOR PROBATION CONFIRMATIONEmp.ID:SD3021300Emp.Name:Bhavitha').click();
  await page.locator('div:nth-child(3) > .row > div:nth-child(8) > div > .ng-star-inserted > .d-flex').click();
  await page.locator('div:nth-child(3) > .row > div:nth-child(9) > div > .ng-star-inserted > .d-flex > #checkformheader').check();
  await page.locator('div:nth-child(4) > .row > div:nth-child(10) > div > .ng-star-inserted > .d-flex > #checkformheader').check();
  await page.locator('div:nth-child(5) > .row > div:nth-child(6) > div > .ng-star-inserted > .d-flex > #checkformheader').check();
  await page.getByRole('textbox', { name: 'Text area' }).click();
  await page.getByRole('textbox', { name: 'Text area' }).fill('we');
  await page.getByRole('textbox', { name: 'Text area' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Text area' }).fill('weFF');
  await page.getByRole('textbox', { name: 'Text area' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Text area' }).fill('Test Text Area');
  await page.getByText('/250').click();
  await page.locator('div').filter({ hasText: /^No$/ }).nth(1).click();
  await page.locator('#checkformfooter').nth(1).check();
  await page.getByText('Overall rating:').click();
  await page.getByText('Overall rating:').click();
  await page.locator('div').filter({ hasText: /^Note:Please fill all the fields$/ }).click();
  await page.getByRole('button', { name: 'Cancel' }).click();
  await page.getByRole('button', { name: 'No' }).click();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByText('Are you sure you want to').click();
  const downloadPromise = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Yes' }).click();
  const download = await downloadPromise;
  await page.getByText('Assessment form submitted').click();
  await page.getByRole('button', { name: 'OK' }).click();
  await page.getByText('Confirmed').click();
  await page.getByText('Extend', { exact: true }).click();
  await page.getByText('Reject').click();
  await page.getByRole('textbox', { name: 'Description' }).click();
  await page.getByRole('textbox', { name: 'Description' }).fill('Test Reject ');
  await page.getByRole('button', { name: 'Cancel' }).click();
  await page.getByText('Are you sure you want to').click();
  await page.getByRole('button', { name: 'No' }).click();
  // Phase 2 — RM Reject probation decision
  await page.getByRole('radio', { name: 'Reject' }).check();
  await page.getByRole('textbox', { name: 'Description' }).click();
  await page.getByRole('textbox', { name: 'Description' }).fill('Test Reject ');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByText('Confirm Probation status?').click();
  await page.getByText('Probation request rejected').click();
  await page.locator('.custom-table-content').click();
  // Phase 3 — TM Reject probation decision (same user as RM; second pending record)
  await page.getByText('Pending Approvals').click();
  await page.locator('div').filter({ hasText: /^Onboarding\(\d+\)$/ }).first().click();
  await page.getByText(/^Probation\(\d+\)$/).click();
  await page.getByRole('button', { name: 'Assessment form' }).click();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('button', { name: 'Yes' }).click();
  await page.getByRole('button', { name: 'OK' }).click();
  await page.getByRole('radio', { name: 'Reject' }).check();
  await page.getByRole('textbox', { name: 'Description' }).fill('Reject the Probation TM');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByText('Probation request rejected').click();
  await page.getByText('Employees').click();
  await page.getByRole('searchbox', { name: 'Username' }).click();
  await page.getByRole('searchbox', { name: 'Username' }).fill('bhav');
  await page.getByText('Probation').click();
  await page.getByRole('searchbox', { name: 'Username' }).click();
  await page.getByRole('searchbox', { name: 'Username' }).fill('bhav');
  await page.getByText('Bhavitha Reddy').click();
  await page.getByText('Job').click();
  await page.locator('div').filter({ hasText: /^Probation Info$/ }).nth(1).click();
  await page.getByRole('cell', { name: 'Rejected' }).click();
  await page.locator('app-probation-details').getByText('Probation Info').click();
  await page.getByRole('cell', { name: 'Rejected' }).click();
  await page.getByRole('cell').filter({ hasText: 'Re-Request for Probation' }).click();
  await page.getByText('Re-Request for Probation').click();
  await page.locator('#pn_id_7').click();
  await page.getByRole('cell', { name: 'Waiting for Approval' }).click();
  // Phase 5 — HR Process Reject (3rd level after RM/TM reject)
  await page.getByText('Pending Approvals').click();
  await page.locator('div').filter({ hasText: /^Onboarding\(\d+\)$/ }).first().click();
  await page.getByText(/^Probation\(\d+\)$/).click();
  await page.getByRole('button', { name: 'Process' }).click();
  await page.getByText('Are you sure you want to Process?').click();
  await page.getByRole('radio', { name: 'Reject' }).check();
  await page.getByRole('textbox', { name: 'Description' }).fill('HR Process Reject probation');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByText('Probation request rejected').click();
  // Phase 6 — Re-request from Rejected, RM/TM Extend, Approved + approver history
  await page.getByRole('cell', { name: 'Rejected' }).click();
  await page.getByRole('cell').filter({ hasText: 'Re-Request for Probation' }).click();
  await page.getByText('Re-Request for Probation').click();
  await page.getByText('Probation request raised').click();
  await page.getByText('Pending Approvals').click();
  await page.locator('div').filter({ hasText: /^Onboarding\(\d+\)$/ }).first().click();
  await page.getByText(/^Probation\(\d+\)$/).click();
  await page.getByRole('button', { name: 'Assessment form' }).click();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('button', { name: 'Yes' }).click();
  await page.getByRole('button', { name: 'OK' }).click();
  await page.getByRole('radio', { name: 'Extend' }).check();
  await page.getByRole('textbox', { name: 'Feedback for Extend *' }).fill('Extend probation feedback RM');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('cell', { name: 'Approved' }).click();
  await page.locator('app-probation-details table tbody tr').filter({ hasText: 'Approved' }).locator('td').nth(5).locator('div').first().click();
  await page.getByText('Approver History').click();
  await page.getByRole('columnheader', { name: 'Approver Role' }).click();
  await page.getByRole('cell', { name: 'TM', exact: true }).click();
  await page.getByRole('cell', { name: 'RM', exact: true }).click();
  await page.getByRole('cell', { name: 'Extended', exact: true }).first().click();
  // Phase 7 — HR Process Extend from Pending Approvals Probation queue
  await page.getByText('Pending Approvals').click();
  await page.locator('div').filter({ hasText: /^Onboarding\(\d+\)$/ }).first().click();
  await page.getByText(/^Probation\(\d+\)$/).click();
  await page.getByRole('button', { name: 'Process' }).click();
  await page.getByText('Are you sure you want to Process?').click();
  await page.getByRole('radio', { name: 'Extend' }).check();
  await page.getByRole('textbox', { name: 'Default select example' }).click();
  await page.keyboard.press('ArrowDown');
  await page.keyboard.press('Enter');
  await page.getByRole('textbox', { name: /Feedback for Extend/i }).fill('Test Process HR Extend');
  await page.getByRole('button', { name: 'Submit' }).click();
  // Phase 8 — Confirm from Extended: raise request, RM/TM Confirm, HR Process
  await page.getByRole('cell', { name: 'Extended' }).click();
  await page.getByRole('cell').filter({ hasText: 'Request for Probation' }).click();
  await page.getByText('Request for Probation').click();
  await page.getByText('Probation request raised').click();
  await page.getByText('Pending Approvals').click();
  await page.locator('div').filter({ hasText: /^Onboarding\(\d+\)$/ }).first().click();
  await page.getByText(/^Probation\(\d+\)$/).click();
  await page.getByRole('button', { name: 'Assessment form' }).click();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('button', { name: 'Yes' }).click();
  await page.getByRole('button', { name: 'OK' }).click();
  await page.getByRole('radio', { name: 'Confirmed' }).check();
  await page.getByRole('textbox', { name: /Description|Comments/i }).fill('Confirm probation decision');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByText('Probation request approved').click();
  await page.getByRole('cell', { name: 'Approved' }).click();
  await page.locator('app-probation-details table tbody tr').filter({ hasText: 'Approved' }).locator('td').nth(5).locator('div').first().click();
  await page.getByText('Approver History').click();
  await page.getByText('Pending Approvals').click();
  await page.locator('div').filter({ hasText: /^Onboarding\(\d+\)$/ }).first().click();
  await page.getByText(/^Probation\(\d+\)$/).click();
  await page.getByRole('button', { name: 'Process' }).click();
  await page.getByText('Are you sure you want to Process?').click();
  await page.getByRole('radio', { name: 'Process' }).check();
  await page.getByRole('textbox', { name: 'Comments*' }).fill('HR Process confirm probation');
  await page.getByRole('button', { name: 'Submit' }).click();
  // Phase 9 — Generate Documents: Probation Confirmation Letter → Release → Active tab
  await page.getByText('Employees').click();
  await page.getByRole('button', { name: 'Generate Documents' }).click();
  await page.locator('div').filter({ hasText: /^Probation Confirmation Letter$/ }).first().click();
  await page.getByRole('combobox', { name: 'Please select employee' }).click();
  await page.getByRole('option', { name: 'SD3021300-Bhavitha Reddy' }).click();
  await page.getByPlaceholder('Please enter Date').first().fill('2026-09-08');
  await page.getByPlaceholder('Please enter Date').nth(1).fill('2026-09-08');
  await page.getByRole('combobox', { name: 'Please select document type' }).click();
  await page.getByRole('option', { name: 'Soft Copy' }).click();
  await page.getByRole('combobox', { name: 'Please select signature' }).click();
  await page.getByRole('option', { name: 'saii Pavan Dinesh Tejaa' }).click();
  const downloadPromise = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Generate Document' }).click();
  await downloadPromise;
  await page.getByText('Probation confirmation letter generated successfully').click();
  await page.getByRole('button', { name: 'Release Letter' }).click();
  await page.getByText('Email has been sent').click();
  await page.getByText('Employees').click();
  await page.getByText(/^Active\(\d+\)$/).click();
  await page.getByRole('searchbox', { name: 'Username' }).fill('bhav');
  await page.getByRole('searchbox', { name: 'Username' }).press('Enter');
  await page.getByRole('cell', { name: 'Bhavitha Reddy' }).click();
});