import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://hrmsqarightlyhr.onpremise.cluster.rightlyhr.com/login');
  await page.getByRole('textbox', { name: 'Please enter email' }).click();
  await page.getByRole('textbox', { name: 'Please enter email' }).fill('pavan.nedunuri@snaddevelopers.com');
  await page.getByRole('textbox', { name: 'Please enter password' }).click();
  await page.getByRole('textbox', { name: 'Please enter password' }).fill('Pavan@123');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.goto('https://hrmsqarightlyhr.onpremise.cluster.rightlyhr.com/dashboard/emp');
  await page.getByText('Employees').click();
  await page.getByRole('searchbox', { name: 'Username' }).click();
  await page.getByRole('searchbox', { name: 'Username' }).fill('saii');
  await page.locator('#pn_id_2-table').getByText('saii Pavan Dinesh Tejaa').click();
  await page.getByText('Job').click();
  await page.locator('div').filter({ hasText: /^Job Info$/ }).nth(1).click();
  await page.getByRole('link', { name: 'WFH / Remote Login' }).click();
  await page.locator('.dropdown.ng-star-inserted').click();
  await page.getByText('Update').click();
  await page.locator('#pn_id_15').getByRole('button', { name: 'dropdown trigger' }).click();
  await page.locator('#pn_id_15').getByRole('button', { name: 'dropdown trigger' }).click();
  await page.getByRole('textbox').fill('2026-09-02');
  await page.getByRole('button', { name: 'Update' }).click();
  await page.getByRole('dialog').click();
  await page.getByText('Allocate', { exact: true }).click();
  await page.locator('#pn_id_25').getByRole('button', { name: 'dropdown trigger' }).click();
  await page.getByRole('option', { name: 'Yes' }).click();
  await page.getByText('\'Work From Home\' is already').click();
  await page.locator('#pn_id_23').getByRole('button', { name: 'dropdown trigger' }).click();
  await page.getByRole('option', { name: 'No' }).click();
  await page.locator('#pn_id_31').getByRole('button', { name: 'dropdown trigger' }).click();
  await page.getByText('Remote', { exact: true }).click();
  await page.getByRole('combobox', { name: 'Select Remote Login Manager' }).click();
  await page.getByText('SD302262 - saii Pavan Dinesh').click();
  await page.locator('#pn_id_31').getByRole('button', { name: 'dropdown trigger' }).click();
  await page.getByRole('option', { name: 'Hybrid' }).click();
  await page.getByText('Cancel Submit').click();
  await page.locator('#pn_id_31').getByRole('button', { name: 'dropdown trigger' }).click();
  await page.getByRole('option', { name: 'Remote' }).click();
  await page.getByText('Work From Home Allow Work').click();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('button', { name: 'Cancel' }).click();
  await page.locator('.dropdown.ng-star-inserted').click();
  await page.getByText('Inactive').click();
  await page.getByRole('button', { name: 'Yes' }).click();
  await page.getByText('Allocate', { exact: true }).click();
  await page.locator('#pn_id_37').getByRole('button', { name: 'dropdown trigger' }).click();
  await page.getByRole('option', { name: 'Yes' }).click();
  await page.locator('#pn_id_39').getByRole('button', { name: 'dropdown trigger' }).click();
  await page.getByText('Remote', { exact: true }).click();
  await page.getByRole('combobox', { name: 'Select Remote Login Manager' }).click();
  await page.getByText('SD302262 - saii Pavan Dinesh').click();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByText('Remote Login manager').click();
  await page.goto('https://hrmsqarightlyhr.onpremise.cluster.rightlyhr.com/dashboard/emp');
  await page.locator('#sidenav-main-drop > div:nth-child(3)').click();
  await page.locator('div').filter({ hasText: /^Remote Login$/ }).first().click();
  await page.getByRole('button', { name: ' Request Remote Login' }).click();
  await page.getByRole('textbox', { name: 'Worked Date *' }).fill('2026-09-02');
  await page.getByRole('radio', { name: 'Half Day' }).check();
  await page.getByRole('radio', { name: 'First Half' }).check();
  await page.getByRole('textbox', { name: 'Reason*' }).click();
  await page.getByRole('textbox', { name: 'Reason*' }).fill('request remote login');
  await page.getByRole('button', { name: 'Cancel' }).click();
  await page.getByRole('button', { name: 'Yes' }).click();
  await page.getByRole('button', { name: ' Request Remote Login' }).click();
  await page.getByRole('textbox', { name: 'Worked Date *' }).fill('2026-09-02');
  await page.getByRole('radio', { name: 'Half Day' }).check();
  await page.getByRole('radio', { name: 'First Half' }).check();
  await page.getByRole('textbox', { name: 'Reason*' }).click();
  await page.getByRole('textbox', { name: 'Reason*' }).fill('Request remote login');
  await page.getByRole('button', { name: 'Request' }).click();
  await page.locator('div').filter({ hasText: 'Remote Login request' }).nth(2).click();
  await page.getByText('Remote Login request').click();
  await page.getByText('Pending Approvals').click();
  await page.getByText('Pending Approvals').click();
  await page.getByText('Pending Approvals').click();
  await page.locator('#sidenav-main-drop > div:nth-child(9)').click();
  await page.getByText('Time-Off(17)').click();
  await page.getByText('Remote Login(1)').click();
  await page.getByRole('row', { name: 'SD302262 saii Pavan Dinesh' }).getByRole('checkbox').check();
  await page.getByRole('button', { name: 'Process' }).click();
  await page.locator('div').filter({ hasText: 'Total RecordsSuccess' }).nth(3).click();
  await page.getByRole('dialog').click();
  await page.locator('#sidenav-main-drop > div:nth-child(3)').click();
  await page.locator('div').filter({ hasText: /^Remote Login$/ }).nth(1).click();
  await page.locator('div').filter({ hasText: /^Processed \(1\)$/ }).first().click();
  await page.locator('div').filter({ hasText: /^Waiting For Approval \(0\)$/ }).first().click();
  await page.getByRole('button', { name: ' Request Remote Login' }).click();
  await page.getByRole('textbox', { name: 'Worked Date *' }).fill('2026-09-02');
  await page.getByRole('radio', { name: 'Half Day' }).check();
  await page.getByRole('radio', { name: 'Second Half' }).check();
  await page.getByRole('textbox', { name: 'Reason*' }).click();
  await page.getByRole('textbox', { name: 'Reason*' }).fill('Request Remote login 2nd half ');
  await page.getByRole('button', { name: 'Request' }).click();
  await page.getByText('Remote Login request').click();
  await page.getByText('Pending Approvals').click();
  await page.getByText('Pending Approvals').click();
  await page.getByText('Pending Approvals').click();
  await page.getByText('Pending Approvals').click();
  await page.getByText('Pending Approvals').click();
  await page.getByText('Pending Approvals').click();
  await page.getByText('Pending Approvals').click();
  await page.locator('div:nth-child(9) > .btn-group > div > .main-menu-icon').click();
  await page.getByText('Pending Approvals').click();
  await page.getByText('Pending Approvals').click();
  await page.locator('#sidenav-main-drop > div:nth-child(9)').click();
  await page.locator('div').filter({ hasText: /^Time-Off\(17\)$/ }).first().click();
  await page.getByText('Remote Login(1)').click();
  await page.getByRole('row', { name: 'SD302262 saii Pavan Dinesh' }).getByRole('checkbox').check();
  await page.getByRole('button', { name: 'Reject' }).click();
  await page.getByRole('button', { name: 'Rejected' }).click();
  await page.getByRole('button', { name: 'Reject', exact: true }).click();
});