import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
    await page.goto('https://hrmsqarightlyhr.onpremise.cluster.rightlyhr.com/login');
    await page.getByRole('textbox', { name: 'Please enter email' }).click();
    await page.getByRole('textbox', { name: 'Please enter email' }).click();
    await page.getByRole('textbox', { name: 'Please enter email' }).fill('I');
    await page.getByRole('textbox', { name: 'Please enter email' }).press('CapsLock');
    await page.getByRole('textbox', { name: 'Please enter email' }).fill('Indu@yopmail.com');
    await page.getByRole('textbox', { name: 'Please enter password' }).click();
    await page.getByRole('textbox', { name: 'Please enter password' }).press('CapsLock');
    await page.getByRole('textbox', { name: 'Please enter password' }).fill('I');
    await page.getByRole('textbox', { name: 'Please enter password' }).press('CapsLock');
    await page.getByRole('textbox', { name: 'Please enter password' }).fill('Indu@123');
    await page.getByRole('textbox', { name: 'Please enter password' }).press('Enter');
    await page.locator('i').click();
    await page.getByRole('button', { name: 'Login' }).click();
    await page.goto('https://hrmsqarightlyhr.onpremise.cluster.rightlyhr.com/dashboard/emp');
    await page.getByText('Attendance', { exact: true }).click();
    await page.locator('a').filter({ hasText: 'Regularization' }).click();
    await page.getByText('Logged Duration: 05:25:').click();
    await page.getByRole('combobox', { name: 'Please select duration' }).click();
    await page.getByRole('option', { name: '0.5' }).click();
    await page.getByRole('combobox', { name: 'Please select regularization' }).click();
    await page.getByRole('option', { name: 'Missed Punch IN' }).click();
    await page.getByRole('textbox', { name: 'Reason*' }).click();
    await page.getByRole('textbox', { name: 'Reason*' }).press('CapsLock');
    await page.getByRole('textbox', { name: 'Reason*' }).fill('P');
    await page.getByRole('textbox', { name: 'Reason*' }).press('CapsLock');
    await page.getByRole('textbox', { name: 'Reason*' }).fill('Punchin missed');
    await page.getByRole('button', { name: 'Request' }).click();
    await page.locator('div').filter({ hasText: 'Regularization request' }).nth(2).click();
    await page.goto('https://hrmsqarightlyhr.onpremise.cluster.rightlyhr.com/login');
    await page.getByRole('textbox', { name: 'Please enter email' }).fill('bhavitha.palagiri@snaddevelopers.com');
    await page.getByRole('textbox', { name: 'Please enter email' }).press('Tab');
    await page.getByRole('textbox', { name: 'Please enter password' }).press('CapsLock');
    await page.getByRole('textbox', { name: 'Please enter password' }).fill('B');
    await page.getByRole('textbox', { name: 'Please enter password' }).press('CapsLock');
    await page.getByRole('textbox', { name: 'Please enter password' }).fill('Bhavi@16');
    await page.getByRole('textbox', { name: 'Please enter password' }).press('Enter');
    await page.goto('https://hrmsqarightlyhr.onpremise.cluster.rightlyhr.com/pending-approvals/time-off/regularization-request/for-you');
    await page.locator('div').filter({ hasText: /^No Data Found\.\.\.$/ }).nth(1).click();
    await page.getByRole('img', { name: 'Profile Image' }).click();
    await page.getByRole('button', { name: 'LogoutLogout' }).click();
    await page.getByRole('button', { name: 'Yes' }).click();
    await page.getByRole('textbox', { name: 'Please enter email' }).click();
    await page.getByRole('textbox', { name: 'Please enter email' }).fill('indu@yopmail.com');
    await page.getByRole('textbox', { name: 'Please enter password' }).click();
    await page.getByRole('textbox', { name: 'Please enter password' }).press('CapsLock');
    await page.getByRole('textbox', { name: 'Please enter password' }).fill('I');
    await page.getByRole('textbox', { name: 'Please enter password' }).press('CapsLock');
    await page.getByRole('textbox', { name: 'Please enter password' }).fill('Indu@123');
    await page.getByRole('textbox', { name: 'Please enter password' }).press('Enter');
    await page.getByRole('button', { name: 'Login' }).click();
    await page.locator('i').click();
    await page.getByText('Attendance', { exact: true }).click();
    await page.getByText('Attendance', { exact: true }).click();
    await page.locator('a').nth(5).click();
    await page.locator('.custom-poup-header-content > div:nth-child(2) > a').click();
    await page.locator('a').filter({ hasText: 'Regularization' }).click();
    await page.getByRole('combobox', { name: 'Please select duration' }).click();
    await page.getByRole('option', { name: '0.5' }).click();
    await page.getByRole('combobox', { name: 'Please select regularization' }).click();
    await page.locator('#leaveType_0').click();
    await page.getByRole('textbox', { name: 'Reason*' }).click();
    await page.getByRole('textbox', { name: 'Reason*' }).press('CapsLock');
    await page.getByRole('textbox', { name: 'Reason*' }).fill('P');
    await page.getByRole('textbox', { name: 'Reason*' }).press('CapsLock');
    await page.getByRole('textbox', { name: 'Reason*' }).fill('Punchout missed');
    await page.getByRole('button', { name: 'Request' }).click();
    await page.getByText('Regularization request').click();
    await page.locator('a').nth(5).click();
    await page.getByRole('button', { name: 'Regularizations' }).click();
    await page.locator('.custom-poup-header-content > div:nth-child(2) > a').click();
    await page.locator('path').nth(3).click();
    await page.getByRole('button', { name: 'LogoutLogout' }).click();
    await page.getByRole('button', { name: 'Yes' }).click();
    await page.getByRole('textbox', { name: 'Please enter email' }).click();
    await page.getByRole('textbox', { name: 'Please enter email' }).fill('bhavitha.palagiri@snaddevelopers.com');
    await page.getByRole('textbox', { name: 'Please enter email' }).press('Tab');
    await page.getByRole('textbox', { name: 'Please enter password' }).press('CapsLock');
    await page.getByRole('textbox', { name: 'Please enter password' }).fill('B');
    await page.getByRole('textbox', { name: 'Please enter password' }).press('CapsLock');
    await page.getByRole('textbox', { name: 'Please enter password' }).fill('Bhavi@16');
    await page.getByRole('textbox', { name: 'Please enter password' }).press('Enter');
    await page.locator('i').click();
    await page.getByRole('button', { name: 'Login' }).click();
    await page.getByText('Attendance', { exact: true }).click();
    await page.getByRole('combobox', { name: 'Select Employee' }).click();
    await page.getByRole('searchbox').fill('indu');
    await page.getByText('SD302133 - Indu Priya').click();
    await page.getByText('Regularized(Requested)').click();
    await page.getByText('Time Off').click();
    await page.getByText('Pending Approvals').click();
    await page.locator('div').filter({ hasText: /^Time-Off\(15\)$/ }).first().click();
    await page.getByText('Regularizations').click();
    await page.locator('p-tablecheckbox > .ng-untouched > .p-checkbox > .p-checkbox-box').click();
    await page.goto('https://hrmsqarightlyhr.onpremise.cluster.rightlyhr.com/login');
    await page.getByRole('textbox', { name: 'Please enter email' }).fill('indu@yopmail.com');
    await page.getByRole('textbox', { name: 'Please enter email' }).press('Tab');
    await page.getByRole('textbox', { name: 'Please enter password' }).press('CapsLock');
    await page.getByRole('textbox', { name: 'Please enter password' }).fill('I');
    await page.getByRole('textbox', { name: 'Please enter password' }).press('CapsLock');
    await page.getByRole('textbox', { name: 'Please enter password' }).fill('Indu@123');
    await page.goto('https://hrmsqarightlyhr.onpremise.cluster.rightlyhr.com/attendance');
    await page.getByRole('textbox', { name: 'Reason*' }).fill('punch missed');
    await page.goto('https://hrmsqarightlyhr.onpremise.cluster.rightlyhr.com/login');
    await page.getByRole('textbox', { name: 'Please enter email' }).fill('bhavitha.palagiri@snaddevelopers.com');
    await page.getByRole('textbox', { name: 'Please enter email' }).press('Tab');
    await page.getByRole('textbox', { name: 'Please enter password' }).press('CapsLock');
    await page.getByRole('textbox', { name: 'Please enter password' }).fill('B');
    await page.getByRole('textbox', { name: 'Please enter password' }).press('CapsLock');
    await page.getByRole('textbox', { name: 'Please enter password' }).fill('Bhavi@16');
    await page.goto('https://hrmsqarightlyhr.onpremise.cluster.rightlyhr.com/pending-approvals/time-off/permissions/for-you');
    await page.getByText('Regularizations(1)').click();
    await page.locator('p-tablecheckbox > .ng-untouched > .p-checkbox > .p-checkbox-box').click();
    await page.goto('https://hrmsqarightlyhr.onpremise.cluster.rightlyhr.com/attendance');
    await page.getByRole('searchbox').fill('indu');
    await page.goto('https://hrmsqarightlyhr.onpremise.cluster.rightlyhr.com/login');
    await page.getByRole('textbox', { name: 'Please enter email' }).fill('indu@yopmail.com');
    await page.getByRole('textbox', { name: 'Please enter email' }).press('Tab');
    await page.getByRole('textbox', { name: 'Please enter password' }).press('CapsLock');
    await page.getByRole('textbox', { name: 'Please enter password' }).fill('I');
    await page.getByRole('textbox', { name: 'Please enter password' }).press('CapsLock');
    await page.getByRole('textbox', { name: 'Please enter password' }).fill('Indu@123');
    await page.goto('https://hrmsqarightlyhr.onpremise.cluster.rightlyhr.com/time-off/regularization/process');
});