import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
    await page.goto('https://hrmsqarightlyhr.onpremise.cluster.rightlyhr.com/login');
    await page.getByRole('textbox', { name: 'Please enter email' }).click();
    await page.getByRole('textbox', { name: 'Please enter email' }).fill('indu@yopmail.com');
    await page.getByRole('textbox', { name: 'Please enter password' }).click();
    await page.getByRole('textbox', { name: 'Please enter password' }).press('CapsLock');
    await page.getByRole('textbox', { name: 'Please enter password' }).fill('I');
    await page.getByRole('textbox', { name: 'Please enter password' }).press('CapsLock');
    await page.getByRole('textbox', { name: 'Please enter password' }).fill('Indu@123');
    await page.getByRole('button', { name: 'Login' }).click();
    await page.getByText('Time Off').click();
    await page.locator('div').filter({ hasText: /^Permissions$/ }).nth(1).click();
    await page.getByText('Time OffPermissions').click();
    await page.getByRole('button', { name: 'Request Permission' }).click();
    await page.getByRole('textbox', { name: 'Date*' }).fill('2026-09-09');
    await page.locator('#duration').getByRole('button', { name: 'dropdown trigger' }).click();
    await page.getByRole('option', { name: '0.5' }).click();
    await page.getByRole('combobox', { name: 'Please select permission type' }).click();
    await page.getByRole('option', { name: 'Early Logout' }).click();
    await page.getByRole('textbox', { name: 'Reason*' }).click();
    await page.getByRole('textbox', { name: 'Reason*' }).press('CapsLock');
    await page.getByRole('textbox', { name: 'Reason*' }).fill('R');
    await page.getByRole('textbox', { name: 'Reason*' }).press('CapsLock');
    await page.getByRole('textbox', { name: 'Reason*' }).fill('Requesting for early ');
    await page.getByRole('textbox', { name: 'Reason*' }).press('CapsLock');
    await page.getByRole('textbox', { name: 'Reason*' }).fill('Requesting for early L');
    await page.getByRole('textbox', { name: 'Reason*' }).press('CapsLock');
    await page.getByRole('textbox', { name: 'Reason*' }).fill('Requesting for early Logout');
    await page.getByRole('textbox', { name: 'Reason*' }).click();
    await page.getByRole('button', { name: 'Request' }).click();
    await page.getByText('Permission request submitted').click();
    await page.getByRole('cell', { name: 'Waiting for Approval' }).click();
    await page.locator('a').nth(4).click();
    await page.getByText('Cancel Permission').click();
    await page.getByText('Are you sure you want to').click();
    await page.getByRole('textbox', { name: 'Please enter cancellation' }).click();
    await page.getByRole('textbox', { name: 'Please enter cancellation' }).fill('cancellation');
    await page.getByRole('button', { name: 'Submit' }).click();
    await page.getByText('Permission cancelled').click();
    await page.locator('div').filter({ hasText: /^No Data Found\.\.\.$/ }).nth(1).click();
    await page.getByText('Waiting For Approval (0)').click();
    await page.locator('div').filter({ hasText: /^No Data Found\.\.\.$/ }).nth(1).click();
    await page.getByRole('button', { name: 'Request Permission' }).click();
    await page.getByRole('textbox', { name: 'Date*' }).fill('2026-09-09');
    await page.locator('#duration').getByRole('button', { name: 'dropdown trigger' }).click();
    await page.getByRole('option', { name: '0.5' }).click();
    await page.getByRole('combobox', { name: 'Please select permission type' }).click();
    await page.getByText('In Between Breaks').click();
    await page.getByText('In Between Breaks').click();
    await page.getByText('In Between Breaks').click();
    await page.getByRole('textbox', { name: 'Reason*' }).click();
    await page.getByRole('textbox', { name: 'Reason*' }).click();
    await page.getByRole('textbox', { name: 'Reason*' }).press('CapsLock');
    await page.getByRole('textbox', { name: 'Reason*' }).fill('B');
    await page.getByRole('textbox', { name: 'Reason*' }).press('CapsLock');
    await page.getByRole('textbox', { name: 'Reason*' }).fill('Break exceeded');
    await page.getByRole('button', { name: 'Request' }).click();
    await page.getByText('Permission request submitted').click();
    await page.getByRole('cell', { name: 'Waiting for Approval' }).click();
    await page1.getByRole('textbox', { name: 'Please enter email' }).click();
    await page1.getByRole('textbox', { name: 'Please enter email' }).fill('bhavitha.palagiri@snaddevelopers.com');
    await page1.getByRole('textbox', { name: 'Please enter password' }).click();
    await page1.getByRole('textbox', { name: 'Please enter password' }).press('CapsLock');
    await page1.getByRole('textbox', { name: 'Please enter password' }).fill('B');
    await page1.getByRole('textbox', { name: 'Please enter password' }).press('CapsLock');
    await page1.getByRole('textbox', { name: 'Please enter password' }).fill('Bhavi@16');
    await page1.getByRole('button', { name: 'Login' }).click();
    await page1.getByText('Pending Approvals').click();
    await page1.getByText('Pending Approvals').click();
    await page1.getByText('Pending Approvals').click();
    await page1.getByText('Pending Approvals').click();
    await page1.getByText('Pending Approvals').click();
    await page1.locator('div:nth-child(9) > .btn-group > div > .main-menu-icon').click();
    await page1.getByText('Pending Approvals').click();
    await page1.getByText('Pending Approvals').click();
    await page1.getByText('Pending Approvals').click();
    await page1.locator('div:nth-child(9) > .btn-group > div > .main-menu-icon').click();
    await page1.getByText('Pending Approvals').click();
    await page1.getByText('Pending Approvals').click();
    await page1.getByText('Pending Approvals').click();
    await page1.locator('div').filter({ hasText: /^13:28:20September 9, 2026$/ }).first().click();
    await page.goto('https://hrmsqarightlyhr.onpremise.cluster.rightlyhr.com/dashboard/emp');
    await page.getByText('Time Off').click();
    await page.getByText('Time Off').click();
    await page.locator('#sidenav-main-drop > div:nth-child(2)').click();
    await page.locator('div').filter({ hasText: /^Permissions$/ }).nth(1).click();
    await page.getByText('Rejected (1)').click();
    await page.locator('a').nth(4).click();
    await page.getByRole('tooltip', { name: 'Rejected' }).getByRole('paragraph').click();
    await page.locator('#pn_id_3').click();
    await page.getByRole('button', { name: 'Request Permission' }).click();
    await page.getByRole('textbox', { name: 'Date*' }).fill('2026-09-09');
    await page.getByRole('combobox', { name: 'Please select duration' }).click();
    await page.getByRole('textbox', { name: 'Reason*' }).click();
    await page.getByRole('combobox', { name: 'Please select permission type' }).click();
    await page.getByRole('combobox', { name: 'Please select duration' }).click();
    await page.getByRole('option', { name: '0.5' }).click();
    await page.getByRole('combobox', { name: 'Please select permission type' }).click();
    await page.getByText('Early Login').click();
    await page.getByRole('textbox', { name: 'Reason*' }).click();
    await page.getByRole('textbox', { name: 'Reason*' }).press('CapsLock');
    await page.getByRole('textbox', { name: 'Reason*' }).fill('E');
    await page.getByRole('textbox', { name: 'Reason*' }).press('CapsLock');
    await page.getByRole('textbox', { name: 'Reason*' }).fill('Early login permission');
    await page.getByRole('button', { name: 'Request' }).click();
    await page.getByText('Permission request submitted').click();
    await page1.getByRole('textbox', { name: 'Please enter email' }).fill('bhavitha.palagiri@snaddevelopers.com');
    await page1.getByRole('textbox', { name: 'Please enter email' }).press('Tab');
    await page1.getByRole('textbox', { name: 'Please enter password' }).press('CapsLock');
    await page1.getByRole('textbox', { name: 'Please enter password' }).fill('B');
    await page1.getByRole('textbox', { name: 'Please enter password' }).press('CapsLock');
    await page1.getByRole('textbox', { name: 'Please enter password' }).fill('Bhavi@16');
    await page1.getByRole('textbox', { name: 'Please enter password' }).press('Enter');
    await page1.goto('https://hrmsqarightlyhr.onpremise.cluster.rightlyhr.com/pending-approvals/time-off/permissions/for-you');
    await page1.getByRole('searchbox', { name: 'search' }).fill('indu');
    await page.goto('https://hrmsqarightlyhr.onpremise.cluster.rightlyhr.com/login');
    await page.getByRole('textbox', { name: 'Please enter email' }).click();
    await page.getByRole('textbox', { name: 'Please enter email' }).fill('bhavitha.palagiri@snaddevelopers.com');
    await page.getByRole('textbox', { name: 'Please enter email' }).press('Tab');
    await page.getByRole('textbox', { name: 'Please enter password' }).press('CapsLock');
    await page.getByRole('textbox', { name: 'Please enter password' }).fill('B');
    await page.getByRole('textbox', { name: 'Please enter password' }).press('CapsLock');
    await page.getByRole('textbox', { name: 'Please enter password' }).fill('Bhavi@176');
    await page.getByRole('textbox', { name: 'Please enter password' }).press('Enter');
    await page.locator('i').click();
    await page.getByRole('textbox', { name: 'Please enter password' }).click();
    await page.getByRole('textbox', { name: 'Please enter password' }).fill('Bhavi@16');
    await page.getByRole('button', { name: 'Login' }).click();
    await page.locator('rect').first().click();
    await page.locator('#settings-panel-2').click();
    await page.getByText('Attendance Eligibility CriteriaConfigure company-wide criteria for Comp Off,').click();
    await page.getByRole('link', { name: 'Permissions Eligibility' }).click();
    await page.getByRole('cell', { name: 'futureDatesAllowed' }).click();
    await page.locator('.dropdown > a').first().click();
    await page.getByText('Update').first().click();
    await page.getByRole('textbox').click();
    await page.getByRole('textbox').dblclick();
    await page.getByRole('textbox').fill('30');
    await page.getByRole('button', { name: 'Update' }).click();
    await page.getByText('Data updated successfully').click();
    await page.getByRole('cell', { name: 'globalPermissionsDuration' }).click();
    await page.locator('tr:nth-child(3) > td:nth-child(3) > .dropdown > a').click();
    await page.getByText('Update').nth(2).click();
    await page.getByRole('textbox').dblclick();
    await page.getByRole('textbox').fill('8');
    await page.getByRole('button', { name: 'Update' }).click();
    await page.getByText('Data updated successfully').click();
    await page.locator('tr:nth-child(4) > td:nth-child(3) > .dropdown > a').click();
    await page.getByText('Update').nth(3).click();
    await page.getByRole('textbox').dblclick();
    await page.getByRole('textbox').fill('2');
    await page.getByRole('button', { name: 'Update' }).click();
    await page.getByText('Data updated successfully').click();
    await page.getByRole('cell').filter({ hasText: 'Update' }).nth(4).click();
    await page.locator('tr:nth-child(5) > td:nth-child(3) > .dropdown > a').click();
    await page.getByText('Update').nth(4).click();
    await page.getByRole('textbox').dblclick();
    await page.getByRole('textbox').fill('30');
    await page.getByRole('button', { name: 'Update' }).click();
    await page.getByText('Data updated successfully').click();
    await page.getByRole('cell').filter({ hasText: 'Update' }).nth(5).click();
    await page.locator('tr:nth-child(6) > td:nth-child(3) > .dropdown > a').click();
    await page.getByText('Update').nth(5).click();
    await page.getByRole('cell', { name: '18' }).click();
    await page.getByRole('textbox').dblclick();
    await page.getByRole('textbox').fill('10');
    await page.getByRole('button', { name: 'Update' }).click();
    await page.getByText('Data updated successfully').click();
    await page.locator('tr:nth-child(7) > td:nth-child(3) > .dropdown > a').click();
    await page.locator('.dropdown-menu.custom-dropdown-menu.show > li > .dropdown-item').click();
    await page.getByRole('textbox').dblclick();
    await page.getByRole('textbox').fill('3');
    await page.getByRole('button', { name: 'Update' }).click();
    await page.getByText('Data updated successfully').click();
    await page.locator('tr:nth-child(6) > td:nth-child(3) > .dropdown > a').click();
    await page.getByText('Update').nth(5).click();
    await page.getByRole('textbox').click();
    await page.getByRole('textbox').click();
    await page.getByRole('textbox').dblclick();
    await page.getByRole('textbox').fill('16');
    await page.getByRole('button', { name: 'Update' }).click();
    await page.getByText('Data updated successfully').click();
    await page.goto('https://hrmsqarightlyhr.onpremise.cluster.rightlyhr.com/login');
    await page.getByRole('textbox', { name: 'Please enter email' }).click();
    await page.getByRole('textbox', { name: 'Please enter email' }).fill('indu@yopmail.com');
    await page.getByRole('textbox', { name: 'Please enter password' }).click();
    await page.getByRole('textbox', { name: 'Please enter password' }).press('CapsLock');
    await page.getByRole('textbox', { name: 'Please enter password' }).fill('I');
    await page.getByRole('textbox', { name: 'Please enter password' }).press('CapsLock');
    await page.getByRole('textbox', { name: 'Please enter password' }).fill('Indu@123');
    await page.getByRole('button', { name: 'Login' }).click();
    await page.getByText('Time Off').click();
    await page.locator('div').filter({ hasText: /^Permissions$/ }).nth(1).click();
    await page.getByRole('button', { name: 'Request Permission' }).click();
    await page.getByRole('textbox', { name: 'Date*' }).fill('2026-09-11');
    await page.getByRole('combobox', { name: 'Please select duration' }).click();
    await page.getByRole('option', { name: '0.5' }).click();
    await page.getByRole('combobox', { name: 'Please select permission type' }).click();
    await page.getByText('Early Login').click();
    await page.getByRole('textbox', { name: 'Reason*' }).click();
    await page.getByRole('textbox', { name: 'Reason*' }).press('CapsLock');
    await page.getByRole('textbox', { name: 'Reason*' }).fill('R');
    await page.getByRole('textbox', { name: 'Reason*' }).press('CapsLock');
    await page.getByRole('textbox', { name: 'Reason*' }).fill('Requesting early login permission');
    await page.getByRole('button', { name: 'Cancel' }).click();
    await page.getByRole('button', { name: 'Yes' }).click();
    await page.getByRole('button', { name: 'Request Permission' }).click();
    await page.getByRole('textbox', { name: 'Date*' }).fill('2026-09-11');
    await page.getByRole('combobox', { name: 'Please select duration' }).click();
    await page.getByRole('option', { name: '0.5' }).click();
    await page.getByRole('combobox', { name: 'Please select permission type' }).click();
    await page.getByText('Early Login').click();
    await page.getByRole('textbox', { name: 'Reason*' }).click();
    await page.getByRole('textbox', { name: 'Reason*' }).press('CapsLock');
    await page.getByRole('textbox', { name: 'Reason*' }).fill('R');
    await page.getByRole('textbox', { name: 'Reason*' }).press('CapsLock');
    await page.getByRole('textbox', { name: 'Reason*' }).fill('Requesting early login permission');
    await page.getByRole('button', { name: 'Request' }).click();
    await page.getByText('Permission request submitted').click();
    await page.locator('tr:nth-child(3) > td:nth-child(5) > div > a').click();
    await page.getByText('Requesting early login').click();
    await page.getByText('Waiting For Approval (3)').click();
    await page.locator('a').nth(4).click();
    await page.getByRole('listitem').filter({ hasText: 'Cancel Permission' }).locator('a').click();
    await page.getByRole('button', { name: 'Cancel' }).click();
    await page.getByRole('button', { name: 'Yes' }).click();
    await page.locator('#pn_id_2').click();
    await page.getByText('Attendance').click();
    await page.getByRole('cell', { name: 'Sep 11,' }).click();
    await page.getByText('Permission(Requested)', { exact: true }).click();
    await page.getByText('Permission(Requested)', { exact: true }).click();
    await page.locator('tr:nth-child(11) > td:nth-child(5) > .ng-star-inserted > a').click();
    await page.getByText('Attendance Logs (Sep 11, 2026)').click();
    await page.getByRole('button', { name: 'Permissions' }).click();
    await page.getByRole('cell', { name: 'Requested' }).click();
    await page.locator('.custom-poup-header-content > div:nth-child(2) > a').click();
    await page.getByText('Time Off').click();
    await page.locator('div').filter({ hasText: /^Permissions$/ }).nth(1).click();
    await page.locator('tr:nth-child(3) > .text-center.ng-star-inserted > .dropdown').click();
    await page.getByText('Cancel Permission').nth(2).click();
    await page.getByText('Are you sure you want to').click();
    await page.getByRole('textbox', { name: 'Please enter cancellation' }).click();
    await page.getByRole('textbox', { name: 'Please enter cancellation' }).fill('cancelling ');
    await page.getByRole('button', { name: 'Submit' }).click();
    await page.getByText('Permission cancelled').click();
    await page.locator('li:nth-child(3) > .nav-link > .icon').click();
    await page.getByRole('cell', { name: 'Sep 11,' }).click();
    await page.locator('tr:nth-child(3) > td:nth-child(4) > div > a').click();
    await page.locator('tr:nth-child(3) > td:nth-child(5) > div > a').click();
    await page.getByRole('cell', { name: 'Early Login' }).click();
    await page.getByRole('cell', { name: 'Cancelled' }).nth(2).click();
    await page.getByText('Attendance').click();
    await page.locator('tr:nth-child(11) > td:nth-child(2)').click();
    await page.getByText('Time Off').click();
})

