import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://hrmsqarightlyhr.onpremise.cluster.rightlyhr.com/login');
  await page.getByRole('textbox', { name: 'Please enter email' }).click();
  await page.getByRole('textbox', { name: 'Please enter email' }).fill('pavan.nedunuri@snaddevelopers.com');
  await page.getByRole('textbox', { name: 'Please enter password' }).click();
  await page.getByRole('textbox', { name: 'Please enter password' }).fill('Pavan@123');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.goto('https://hrmsqarightlyhr.onpremise.cluster.rightlyhr.com/dashboard/emp');
  await page.locator('#sidenav-main-drop > div:nth-child(8)').click();
  await page.locator('div').filter({ hasText: /^RemoteLogin$/ }).nth(1).click();
  await page.locator('#pn_id_8').getByRole('button', { name: 'dropdown trigger' }).click();
  await page.getByRole('searchbox').click();
  await page.getByRole('searchbox').fill('bhavitha');
  await page.getByRole('option', { name: 'SD3021300 - Bhavitha Reddy' }).click();
  await page.getByRole('button', { name: 'Apply On Behalf Of' }).click();
  await page.getByRole('button', { name: 'Cancel' }).click();
  await page.getByRole('button', { name: 'Yes' }).click();
  await page.locator('timesicon svg').click();
  await page.getByText('Select EmployeePlease select').click();
  await page.getByText('Select Year2026').click();
  await page.getByText('Waiting For Approval (0)').click();
  await page.locator('li:nth-child(2) > .nav-link > .icon').click();
  await page.locator('div').filter({ hasText: /^Processed \(0\)$/ }).first().click();
  await page.locator('div').filter({ hasText: /^Rejected \(0\)$/ }).first().click();
  await page.locator('div').filter({ hasText: /^Cancelled \(0\)$/ }).first().click();
  await page.getByRole('columnheader', { name: 'Worked Date' }).click();
  await page.getByRole('columnheader', { name: 'Availed' }).click();
  await page.getByRole('columnheader', { name: 'Reason', exact: true }).click();
  await page.getByRole('columnheader', { name: 'Cancellation Reason' }).click();
  await page.getByRole('columnheader', { name: 'Cancellation Reason' }).click();
  await page.getByRole('columnheader', { name: 'Applied Date' }).click();
  await page.getByRole('columnheader', { name: 'Status' }).click();
  await page.locator('div').filter({ hasText: /^No Data Found\.\.\.$/ }).nth(1).click();
  await page.locator('#pn_id_8').getByRole('button', { name: 'dropdown trigger' }).click();
  await page.getByRole('searchbox').click();
  await page.getByRole('searchbox').fill('bhavi');
  await page.getByText('SD3021300 - Bhavitha Reddy').click();
  await page.getByRole('button', { name: 'Apply On Behalf Of' }).click();
  await page.getByText('Apply Remote Login On Behalf').click();
  await page.getByText('Availing*Half DayFull Day').click();
  await page.getByRole('textbox', { name: 'Reason *' }).click();
  await page.getByText('Worked Date is required').click();
  await page.getByRole('textbox', { name: 'Worked Date *' }).fill('2026-08-01');
  await page.getByRole('radio', { name: 'Half Day' }).check();
  await page.getByRole('radio', { name: 'First Half' }).check();
  await page.getByRole('textbox', { name: 'Reason *' }).click();
  await page.getByRole('textbox', { name: 'Reason *' }).fill('Request Remote LOgin ');
  await page.getByRole('button', { name: 'Cancel' }).click();
  await page.getByRole('button', { name: 'No' }).click();
  await page.getByRole('button', { name: 'Cancel' }).click();
  await page.getByText('Are you sure you want to').click();
  await page.getByRole('button', { name: 'Yes' }).click();
  await page.getByRole('button', { name: 'Apply On Behalf Of' }).click();
  await page.getByRole('textbox', { name: 'Worked Date *' }).fill('2026-07-01');
  await page.getByRole('radio', { name: 'Half Day' }).check();
  await page.getByRole('radio', { name: 'First Half' }).check();
  await page.getByRole('textbox', { name: 'Reason *' }).click();
  await page.getByRole('textbox', { name: 'Reason *' }).fill('Request Remote Login ');
  await page.getByRole('button', { name: 'Request' }).click();
  await page.locator('div').filter({ hasText: 'Remote login processed' }).nth(3).click();
  await page.getByText('Remote login processed').click();
  await page.locator('div').filter({ hasText: /^Processed \(4\)$/ }).first().click();
  await page.getByRole('cell', { name: 'Apr 1,' }).click();
  await page.getByRole('cell', { name: 'Apr 29,' }).click();
  await page.getByRole('cell', { name: 'Jun 24,' }).click();
  await page.getByRole('cell', { name: 'Jul 1,' }).click();
  await page.getByRole('cell', { name: 'Processed' }).first().click();
  await page.getByRole('cell', { name: 'Processed' }).nth(1).click();
  await page.getByText('Waiting For Approval (3)').click();
  await page.locator('div').filter({ hasText: /^Approved \(0\)$/ }).first().click();
  await page.locator('li:nth-child(4) > .nav-link > .icon').click();
  await page.locator('li:nth-child(5) > .nav-link > .icon').click();
  await page.locator('#sidenav-main-drop > div:nth-child(3)').click();
  await page.locator('div').filter({ hasText: /^Remote Login$/ }).first().click();
  await page.locator('#pn_id_12').getByRole('button', { name: 'dropdown trigger' }).click();
  await page.getByRole('searchbox').click();
  await page.getByRole('searchbox').fill('bhavitha');
  await page.getByRole('option', { name: 'SD3021300 - Bhavitha Reddy' }).click();
  await page.locator('#pn_id_3').getByRole('button', { name: 'dropdown trigger' }).click();
  await page.getByRole('searchbox').click();
  await page.getByRole('searchbox').fill('bhavitha');
  await page.getByText('SD3021300 - Bhavitha Reddy').click();
});