import { test, expect } from '@playwright/test'; 
test('Test-01: Duplicate Employee email trainee creation', async ({ page }) => { 
    await page.goto('https://hrmsqarightlyhr.onpremise.cluster.rightlyhr.com/login'); 
    await page.getByRole('textbox', { name: 'Please enter email' }).click(); 
    await page.getByRole('textbox', { name: 'Please enter email' }).fill('bhavitha.palagiri@snaddevelopers.com'); 
    await page.getByRole('textbox', { name: 'Please enter password' }).click(); 
    await page.getByRole('textbox', { name: 'Please enter password' }).press('CapsLock'); 
    await page.getByRole('textbox', { name: 'Please enter password' }).fill('B'); 
    await page.getByRole('textbox', { name: 'Please enter password' }).press('CapsLock'); 
    await page.getByRole('textbox', { name: 'Please enter password' }).fill('Bhavi@16'); 
    await page.getByRole('button', { name: 'Login' }).click(); 
    await page.getByText('Employees').click(); 
    Click Employees await page.getByText('Employees', { exact: true }).click(); 
    console.log('Employees clicked'); 
    Click Prospective await page.getByText('Prospective', { exact: true }).click(); 
    console.log('prospective clicked'); 
    Click Trainees await page.locator('a[href="/employee-management/prospective/interns"]').click(); 
    console.log('Trainees clicked');
     await page.getByText('Employees', { exact: true }).click(); 
    await page.getByText('Prospective').click(); 
    console.log('prospective clicked'); 
    await page.getByRole('link', { name: 'Trainees (145)' }).click(); 
    await page.getByRole('button', { name: 'Add Prospective Trainee' }).click(); 
    await page.getByRole('textbox', { name: 'Please enter first name' }).click(); 
    await page.getByRole('textbox', { name: 'Please enter first name' }).press('CapsLock');
     await page.getByRole('textbox', { name: 'Please enter first name' }).fill('S'); 
     await page.getByRole('textbox', { name: 'Please enter first name' }).press('CapsLock'); 
     await page.getByRole('textbox', { name: 'Please enter first name' }).fill('Swetha'); 
     await page.getByRole('textbox', { name: 'Please enter last name' }).click();
      await page.getByRole('textbox', { name: 'Please enter last name' }).press('CapsLock'); 
      await page.getByRole('textbox', { name: 'Please enter last name' }).fill('P');
       await page.getByRole('textbox', { name: 'Please enter last name' }).press('CapsLock'); 
       await page.getByRole('textbox', { name: 'Please enter last name' }).fill('Priya'); 
       await page.getByRole('textbox', { name: 'Please enter personal email ID' }).click(); 
       await page.getByRole('textbox', { name: 'Please enter personal email ID' }).press('CapsLock'); 
       await page.getByRole('textbox', { name: 'Please enter personal email ID' }).fill('S'); 
       await page.getByRole('textbox', { name: 'Please enter personal email ID' }).press('CapsLock'); 
       await page.getByRole('textbox', { name: 'Please enter personal email ID' }).fill('Swethapriya@yopmail.com'); 
       await page.getByRole('combobox', { name: 'Please select designation' }).click(); 
       await page.getByRole('option', { name: 'Front End Developer' }).click(); 
       await page.getByRole('combobox', { name: 'Please select employment type' }).click(); 
       await page.getByText('Trainee', { exact: true }).click();
        await page.getByRole('combobox', { name: 'Please select location' }).click(); 
        await page.getByRole('option', { name: 'Hyderabad' }).click(); 
        await page.getByRole('combobox', { name: 'Please select sublocation' }).click(); 
        await page.getByText('Jai Hind Enclave building').click(); 
        await page.getByRole('button', { name: 'Add' }).click(); })
 test('Test-02: New trainee creation', async ({ page }) => {
     await page.goto('https://hrmsqarightlyhr.onpremise.cluster.rightlyhr.com/login'); 
     await page.getByRole('textbox', { name: 'Please enter email' }).click(); 
     await page.getByRole('textbox', { name: 'Please enter email' }).fill('bhavitha.palagiri@snaddevelopers.com'); 
     await page.getByRole('textbox', { name: 'Please enter password' }).click(); 
     await page.getByRole('textbox', { name: 'Please enter password' }).press('CapsLock');
      await page.getByRole('textbox', { name: 'Please enter password' }).fill('B'); 
      await page.getByRole('textbox', { name: 'Please enter password' }).press('CapsLock'); 
      await page.getByRole('textbox', { name: 'Please enter password' }).fill('Bhavi@16'); 
      await page.getByRole('button', { name: 'Login' }).click(); 
      await page.getByText('Employees').click(); 
      Click Employees await page.getByText('Employees', { exact: true }).click(); console.log('Employees clicked'); 
      Click Prospective await page.getByText('Prospective', { exact: true }).click(); 
      console.log('prospective clicked'); 
      Click Trainees await page.locator('a[href="/employee-management/prospective/interns"]').click(); 
      console.log('Trainees clicked'); 
      await page.getByText('Employees', { exact: true }).click(); 
      await page.getByText('Prospective').click(); 
      console.log('prospective clicked');
       await page.getByRole('link', { name: 'Trainees (145)' }).click(); 
      await page.getByRole('button', { name: 'Add Prospective Trainee' }).click(); 
      await page.getByRole('textbox', { name: 'Please enter first name' }).click(); 
      await page.getByRole('textbox', { name: 'Please enter first name' }).press('CapsLock'); 
      await page.getByRole('textbox', { name: 'Please enter first name' }).fill('S'); 
      await page.getByRole('textbox', { name: 'Please enter first name' }).press('CapsLock'); 
      await page.getByRole('textbox', { name: 'Please enter first name' }).fill('Sindhuja'); 
      await page.getByRole('textbox', { name: 'Please enter last name' }).click(); 
      await page.getByRole('textbox', { name: 'Please enter last name' }).press('CapsLock');
       await page.getByRole('textbox', { name: 'Please enter last name' }).fill('P');
       await page.getByRole('textbox', { name: 'Please enter last name' }).press('CapsLock'); 
      await page.getByRole('textbox', { name: 'Please enter last name' }).fill('Priya');
       await page.getByRole('textbox', { name: 'Please enter personal email ID' }).click();
       await page.getByRole('textbox', { name: 'Please enter personal email ID' }).press('CapsLock'); 
      await page.getByRole('textbox', { name: 'Please enter personal email ID' }).fill('S'); 
      await page.getByRole('textbox', { name: 'Please enter personal email ID' }).press('CapsLock'); 
      await page.getByRole('textbox', { name: 'Please enter personal email ID' }).fill('Sindhuja@yopmail.com'); 
      await page.getByRole('combobox', { name: 'Please select designation' }).click();
       await page.getByRole('option', { name: 'Front End Developer' }).click(); 
      await page.getByRole('combobox', { name: 'Please select employment type' }).click(); 
      await page.getByText('Trainee', { exact: true }).click(); 
      await page.getByRole('combobox', { name: 'Please select location' }).click(); 
      await page.getByRole('option', { name: 'Hyderabad' }).click(); 
      await page.getByRole('combobox', { name: 'Please select sublocation' }).click(); 
      await page.getByText('Jai Hind Enclave building').click(); 
      await page.getByRole('button', { name: 'Add' }).click(); })
      test('Test-03: Request documents and verify yopmail', async ({ page }) => {

      import { test, expect } from '@playwright/test';
      test('test', async ({ page }) => {
      await page.goto('https://hrmsqarightlyhr.onpremise.cluster.rightlyhr.com/login');
      await page.getByText('Employee Created').first().click();
      await page.locator('body').press('ArrowLeft');
      await page.locator('body').press('ArrowLeft');
      await page.locator('body').press('ArrowLeft');
      await page.locator('body').press('ArrowLeft');
      await page.locator('body').press('ArrowLeft');
      await page.locator('body').press('ArrowLeft');
      await page.locator('body').press('ArrowLeft');
      await page.locator('body').press('ArrowLeft');
      await page.locator('body').press('ArrowLeft');
      await page.locator('body').press('ArrowLeft');
      await page.locator('body').press('ArrowLeft');
      await page.locator('body').press('ArrowLeft');
      await page.locator('body').press('ArrowLeft');
      await page.locator('body').press('ArrowLeft');
      await page.locator('body').press('ArrowLeft');
      await page.locator('body').press('ArrowLeft');
      await page.getByText('Sindhuja Priya').click();
      await page.getByRole('button', { name: 'Request for Documents' }).click();
      await page.getByText('Email has been sent').click();
      await page1.goto('https://yopmail.com/');
      await page1.getByRole('textbox', { name: 'Login' }).click();
      await page1.getByRole('textbox', { name: 'Login' }).fill('sindhuja');
      await page1.getByRole('textbox', { name: 'Login' }).click();
      await page1.getByRole('textbox', { name: 'Login' }).fill('sindhuja@yopmail.com');
      await page1.getByRole('textbox', { name: 'Login' }).press('Enter');
      await page1.getByTitle('Check Inbox @yopmail.com').click();
      await page1.locator('iframe[name="ifmail"]').contentFrame().getByText('RightlyHR - Sindhuja Priya').click();
      await page1.locator('iframe[name="ifmail"]').contentFrame().getByText('Username :').click();
      await page1.locator('iframe[name="ifmail"]').contentFrame().getByText('Password :').click();
      const page2Promise = page1.waitForEvent('popup');
      await page1.locator('iframe[name="ifmail"]').contentFrame().getByRole('link', { name: 'Click here' }).click();
      const page2 = await page2Promise;
      await page2.getByRole('textbox', { name: 'Username*' }).click();
      await page2.getByRole('textbox', { name: 'Username*' }).press('CapsLock');
      await page2.getByRole('textbox', { name: 'Username*' }).fill('S');
      await page2.getByRole('textbox', { name: 'Username*' }).press('CapsLock');
      await page2.getByRole('textbox', { name: 'Username*' }).fill('Sindhuja@yopmail.com');
      await page1.locator('iframe[name="ifmail"]').contentFrame().getByRole('cell', { name: 'Dear Sindhuja Priya, Welcome to the RightlyHR family! As part of your onboarding journey, we kindly request you to upload the documents listed below. This will help us ensure a smooth and timely onboarding process. Please be assured that all information provided will be handled with the highest level of confidentiality. You can access the onboarding portal using the credentials below: Portal Link : Click here Username : Sindhuja@yopmail.com Password : fsVB&iT! Documents Required: Aadhaar PAN Resume Thank you for choosing to begin your career journey with us! Best regards, RightlyHR', exact: true }).click();
      await page1.locator('iframe[name="ifmail"]').contentFrame().getByRole('cell', { name: 'Dear Sindhuja Priya, Welcome to the RightlyHR family! As part of your onboarding journey, we kindly request you to upload the documents listed below. This will help us ensure a smooth and timely onboarding process. Please be assured that all information provided will be handled with the highest level of confidentiality. You can access the onboarding portal using the credentials below: Portal Link : Click here Username : Sindhuja@yopmail.com Password : fsVB&iT! Documents Required: Aadhaar PAN Resume Thank you for choosing to begin your career journey with us! Best regards, RightlyHR', exact: true }).click();
      await page2.getByRole('textbox', { name: 'Password*' }).click();
      await page2.getByRole('textbox', { name: 'Password*' }).fill('fsVB&iT!');
      await page2.getByRole('button', { name: 'Login' }).click();
      await page2.locator('div').filter({ hasText: 'Application' }).nth(4).click();
      await page2.getByRole('button', { name: 'Go to Application' }).click();
      await page2.getByRole('combobox', { name: 'Please select gender' }).click();
      await page2.getByRole('option', { name: 'Female' }).click();
      await page2.getByRole('combobox', { name: 'Please select salutation' }).click();
      await page2.getByRole('option', { name: 'Miss.' }).click();
      await page2.getByText('Select country').click();
      await page2.locator('lib-country-list').getByRole('textbox').fill('91');
      await page2.getByText('India (भारत)').click();
      await page2.getByRole('textbox', { name: 'Please enter your mobile' }).click();
      await page2.getByRole('textbox', { name: 'Please enter your mobile' }).fill('8678567565');
      await page2.getByRole('textbox', { name: 'Date Of Birth *' }).fill('2000-03-02');
      await page2.getByRole('combobox', { name: 'Please select blood group' }).click();
      await page2.getByRole('option', { name: 'B+', exact: true }).click();
      await page2.locator('#currentAddressLine1').click();
      await page2.locator('#currentAddressLine1').press('CapsLock');
      await page2.locator('#currentAddressLine1').fill('R');
      await page2.locator('#currentAddressLine1').press('CapsLock');
      await page2.locator('#currentAddressLine1').fill('Road no.');
      await page2.locator('#currentAddressLine1').press('CapsLock');
      await page2.locator('#currentAddressLine1').fill('Road no.49');
      await page2.locator('#currentAddressLine1').press('CapsLock');
      await page2.locator('#currentAddressLine1').press('Tab');
      await page2.getByRole('textbox', { name: 'Address Line2' }).press('Tab');
      await page2.locator('#currentCity').press('CapsLock');
      await page2.locator('#currentCity').fill('H');
      await page2.locator('#currentCity').press('CapsLock');
      await page2.locator('#currentCity').fill('Hyderabad');
      await page2.locator('#currentState').click();
      await page2.locator('#currentState').press('CapsLock');
      await page2.locator('#currentState').fill('T');
      await page2.locator('#currentState').press('CapsLock');
      await page2.locator('#currentState').fill('Telangana');
      await page2.getByRole('textbox', { name: 'Country*' }).click();
      await page2.getByRole('textbox', { name: 'Country*' }).press('CapsLock');
      await page2.getByRole('textbox', { name: 'Country*' }).fill('I');
      await page2.getByRole('textbox', { name: 'Country*' }).press('CapsLock');
      await page2.getByRole('textbox', { name: 'Country*' }).fill('India');
      await page2.locator('#currentzipCode').click();
      await page2.locator('#currentzipCode').fill('500012');
      await page2.getByRole('checkbox', { name: 'Same as Current Address' }).check();
      await page2.getByRole('button', { name: 'Next' }).click();
      await page2.getByRole('row', { name: 'Resume* - - - Requested' }).getByRole('button').click();
      await page2.getByRole('button', { name: 'Choose File' }).setInputFiles('Ridhesh__Kumar_1788248807267_Non-DisclosureAgreementLeter_Signed.pdf');
      await page2.getByRole('textbox', { name: 'Document Number' }).click();
      await page2.getByRole('button', { name: 'Upload' }).click();
      await page2.getByRole('row', { name: 'PAN* - - - Requested - - ' }).getByRole('button').click();
      await page2.getByRole('textbox', { name: 'Document Number*' }).click();
      await page2.getByRole('textbox', { name: 'Document Number*' }).press('CapsLock');
      await page2.getByRole('textbox', { name: 'Document Number*' }).fill('EDGDD5645H');
      await page2.getByRole('button', { name: 'Choose File' }).setInputFiles('Ridhesh__Kumar_1788248721927_Non-DisclosureAgreementLetter_Unsigned.pdf');
      await page2.getByRole('button', { name: 'Upload' }).click();
      await page2.getByRole('button', { name: ' Upload' }).click();
      await page2.getByRole('textbox', { name: 'Document Number*' }).click();
      await page2.getByRole('textbox', { name: 'Document Number*' }).fill('877867686786');
      await page2.getByRole('button', { name: 'Choose File' }).setInputFiles('Ridhesh__Kumar_1788247985340_OfferLetter_Signed.pdf');
      await page2.getByRole('button', { name: 'Upload' }).click();
      await page2.getByText('Document uploaded successfully').click();
      await page2.getByRole('button', { name: 'Submit' }).click();
      await page2.getByText('Are you sure you want to').click();
      await page2.getByText('Close Submit').click();
      await page2.getByRole('button', { name: 'Submit' }).click();
      await page2.getByText('Submitted successfully, We’ll').click();
      await page1.locator('iframe[name="ifmail"]').contentFrame().getByText('RightlyHR - Sindhuja Priya -').click();
      await page1.locator('iframe[name="ifmail"]').contentFrame().getByRole('cell', { name: 'Company Logo Image Dear' }).nth(1).click();
      await page.getByText('Job').click();
      await page.locator('div').filter({ hasText: /^Onboarding Documents$/ }).nth(1).click();
      await page.locator('.dropdown > a').first().click();
      await page.locator('.dropdown > a').first().click();
      await page.locator('.dropdown > a').first().click();
      await page.locator('.dropdown > a').first().click();
      await page.locator('.dropdown > a').first().click();
      await page.locator('.dropdown.ng-star-inserted').first().click();
      await page.locator('body').press('ArrowDown');
      await page.locator('body').press('ArrowDown');
      await page.locator('body').press('ArrowDown');
      await page.getByText('Reject').first().click();
      await page.getByRole('textbox', { name: 'Please enter reject reason' }).click();
      await page.getByRole('textbox', { name: 'Please enter reject reason' }).press('CapsLock');
      await page.getByRole('textbox', { name: 'Please enter reject reason' }).fill('r');
      await page.getByRole('textbox', { name: 'Please enter reject reason' }).press('CapsLock');
      await page.getByRole('textbox', { name: 'Please enter reject reason' }).fill('R');
      await page.getByRole('textbox', { name: 'Please enter reject reason' }).press('CapsLock');
      await page.getByRole('textbox', { name: 'Please enter reject reason' }).fill('Rejected ');
      await page.getByText('Close Reject').click();
      await page.getByRole('button', { name: 'Reject' }).click();
      await page.getByText('Document rejected successfully').click();
      await page.locator('tr:nth-child(2) > .text-center.ng-star-inserted > .dropdown > a').click();
      await page.locator('tr:nth-child(2) > .text-center.ng-star-inserted > .dropdown > a').click();
      await page.locator('tr:nth-child(2) > .text-center.ng-star-inserted > .dropdown > a').click();
      await page.locator('tr:nth-child(2) > .text-center.ng-star-inserted > .dropdown > a').click();
      await page.locator('tr:nth-child(2) > .text-center.ng-star-inserted > .dropdown > a').click();
      await page.locator('tr:nth-child(2) > .text-center.ng-star-inserted > .dropdown > a').click();
      await page.getByRole('cell').filter({ hasText: 'VerifyReject' }).nth(1).click();
      await page.getByText('Verify').nth(1).click();
      await page.getByText('Are you sure you want to').click();
      await page.getByText('NoYes').click();
      await page.getByRole('button', { name: 'Yes' }).click();
      await page.getByText('Document verified successfully').click();
      await page.locator('.dropdown > a').click();
      await page.getByRole('cell').filter({ hasText: 'VerifyReject' }).click();
      await page.getByText('Verify').click();
      await page.getByText('Are you sure you want to').click();
      await page.getByRole('button', { name: 'Yes' }).click();
      await page.getByText('Document verified successfully').click();
      await page.getByRole('button', { name: 'Re-Request Documents' }).click();
      await page.getByRole('textbox', { name: 'Please enter comments' }).click();
      await page.getByRole('textbox', { name: 'Please enter comments' }).press('CapsLock');
      await page.getByRole('textbox', { name: 'Please enter comments' }).fill('R');
      await page.getByRole('textbox', { name: 'Please enter comments' }).press('CapsLock');
      await page.getByRole('textbox', { name: 'Please enter comments' }).fill('Rerequest the rejected documents');
      await page.getByText('CloseSubmit').click();
      await page.getByRole('button', { name: 'Re-Request Documents' }).click();
      await page.getByRole('textbox', { name: 'Please enter comments' }).click();
      await page.getByRole('textbox', { name: 'Please enter comments' }).fill('rerequest rejected documents');
      await page.getByRole('button', { name: 'Submit' }).click();
      await page.getByText('Email has been sent').click();
      await page1.locator('#refresh').click();
      await page1.locator('iframe[name="ifmail"]').contentFrame().getByText('Deliverability Reply').click();
      await page1.locator('iframe[name="ifmail"]').contentFrame().getByText('RightlyHR - Sindhuja Priya -').click();
      await page1.locator('iframe[name="ifmail"]').contentFrame().getByRole('cell', { name: 'Company Logo Image Dear' }).nth(1).click();
      await page1.locator('iframe[name="ifmail"]').contentFrame().getByText('Comments :').click();
      await page1.locator('iframe[name="ifmail"]').contentFrame().getByText('Username :').click();
      await page1.locator('iframe[name="ifmail"]').contentFrame().getByText('Password :').click();
      const page3Promise = page1.waitForEvent('popup');
      await page1.locator('iframe[name="ifmail"]').contentFrame().getByRole('link', { name: 'Click here' }).click();
      const page3 = await page3Promise;
      await page3.getByRole('textbox', { name: 'Username*' }).click();
      await page3.getByRole('textbox', { name: 'Username*' }).click();
      await page3.getByRole('textbox', { name: 'Username*' }).press('CapsLock');
      await page3.getByRole('textbox', { name: 'Username*' }).fill('S');
      await page3.getByRole('textbox', { name: 'Username*' }).press('CapsLock');
      await page3.getByRole('textbox', { name: 'Username*' }).fill('Sinshuja@yopmail.com');
      await page3.getByRole('textbox', { name: 'Username*' }).dblclick();
      await page3.getByRole('textbox', { name: 'Username*' }).click();
      await page3.getByRole('textbox', { name: 'Username*' }).fill('Sindhuja@yopmail.com');
      await page3.locator('div:nth-child(2) > .input-group').click();
      await page1.locator('iframe[name="ifmail"]').contentFrame().getByText('Password :').click();
      await page3.getByRole('textbox', { name: 'Password*' }).click();
      await page3.getByRole('textbox', { name: 'Password*' }).fill('fsVB&iT!');
      await page3.locator('i').click();
      await page3.getByRole('textbox', { name: 'Password*' }).click();
      await page3.getByRole('button', { name: 'Login' }).click();
      await page3.getByRole('button', { name: 'Go to Application' }).click();
      await page3.getByRole('button', { name: 'Next' }).click();
      await page3.locator('a').nth(4).click();
      await page3.getByRole('button', { name: ' Re-Upload' }).click();
      await page3.getByRole('button', { name: 'Choose File' }).setInputFiles('Ridhesh__Kumar_1788248721927_Non-DisclosureAgreementLetter_Unsigned.pdf');
      await page3.getByText('Note: Only Pdf and image are').click();
      await page3.getByRole('button', { name: 'Upload' }).click();
      await page3.getByText('Document uploaded successfully').click();
      await page3.getByRole('button', { name: 'Submit' }).click();
      await page3.getByText('Are you sure you want to').click();
      await page3.getByRole('button', { name: 'Submit' }).click();
      await page1.locator('#refresh').click();
      await page1.locator('iframe[name="ifmail"]').contentFrame().getByText('RightlyHR - Sindhuja Priya -').click();
      await page1.locator('iframe[name="ifmail"]').contentFrame().getByRole('cell', { name: 'Company Logo Image Dear' }).nth(1).click();
      await page.getByRole('cell').filter({ hasText: 'VerifyReject' }).click();
      await page.getByText('Verify').click();
      await page.getByText('Are you sure you want to').click();
      await page.getByRole('button', { name: 'Yes' }).click();
      await page.getByText('Document verified successfully').click();
      });