import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://hrmsqarightlyhr.onpremise.cluster.rightlyhr.com/login');
  await page.getByRole('textbox', { name: 'Please enter email' }).click();
  await page.getByRole('textbox', { name: 'Please enter email' }).fill('pavan.nedunuri@snaddevelopers.com');
  await page.getByRole('textbox', { name: 'Please enter password' }).click();
  await page.getByRole('textbox', { name: 'Please enter password' }).fill('Pavan@123');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByRole('img', { name: 'Icon' }).nth(2).click();
  await page.getByRole('searchbox', { name: 'Username' }).click();
  await page.getByRole('searchbox', { name: 'Username' }).fill('pa');
  await page.locator('#pn_id_2-table').getByText('saii Pavan Dinesh Tejaa').click();
  await page.getByText('Job').click();
  await page.locator('div').filter({ hasText: /^Job Info$/ }).first().click();
  await page.getByRole('link', { name: 'WFH / Remote Login' }).click();
  await page.getByText('Allocate', { exact: true }).click();
  await page.getByRole('textbox').fill('2026-08-31');
  await page.locator('#pn_id_15').getByRole('button', { name: 'dropdown trigger' }).click();
  await page.getByRole('option', { name: 'Yes' }).click();
  await page.locator('#pn_id_23').getByRole('button', { name: 'dropdown trigger' }).click();
  await page.getByRole('option', { name: 'Work From Home' }).click();
  await page.getByRole('combobox', { name: 'Select Work From Home Manager' }).click();
  await page.locator('#pn_id_25').getByRole('button', { name: 'dropdown trigger' }).click();
  await page.getByRole('combobox', { name: 'Select Work From Home Manager' }).click();
  await page.getByText('Work From Home Work Location *Work From Home').click();
  await page.getByRole('combobox', { name: 'Work From Home', exact: true }).click();
  await page.getByText('Work From Home Manager *Select Work From Home Manager Work From Home Manager is').click();
  await page.getByRole('combobox', { name: 'Select Work From Home Manager' }).click();
  await page.getByText('Work From Home Manager is').click();
  await page.getByRole('combobox', { name: 'Select Work From Home Manager' }).click();
  await page.getByText('SD302262 - saii Pavan Dinesh').click();
  await page.getByRole('dialog').locator('div').filter({ hasText: /^Remote Login$/ }).click();
  await page.locator('#pn_id_17').getByRole('button', { name: 'dropdown trigger' }).click();
  await page.getByRole('option', { name: 'No' }).click();
  await page.getByRole('button', { name: 'Cancel' }).click();
  await page.locator('#sidenav-main-drop > div:nth-child(3)').click();
  await page.locator('div').filter({ hasText: /^Remote Login$/ }).nth(1).click();
  await page.locator('.cdk-drag.nav-item.menu-item-clear.draggable-nav-item.ng-star-inserted.active-nav-link').click();
  await page.getByText('Employees').click();
  await page.getByRole('searchbox', { name: 'Username' }).click();
  await page.getByRole('searchbox', { name: 'Username' }).fill('saii');
  await page.locator('#pn_id_7-table').getByText('saii Pavan Dinesh Tejaa').click();
  await page.getByText('Job').click();
  await page.locator('div').filter({ hasText: /^Job Info$/ }).first().click();
  await page.getByRole('link', { name: 'WFH / Remote Login' }).click();
  await page.getByText('Allocate', { exact: true }).click();
  await page.locator('#pn_id_42').getByRole('button', { name: 'dropdown trigger' }).click();
  await page.getByRole('option', { name: 'No' }).click();
  await page.locator('#pn_id_40').getByRole('button', { name: 'dropdown trigger' }).click();
  await page.getByRole('option', { name: 'Yes' }).click();
  await page.getByRole('combobox', { name: 'Select Work Location' }).click();
  await page.locator('#pn_id_48').getByRole('button', { name: 'dropdown trigger' }).click();
  await page.getByRole('combobox', { name: 'Select Work Location' }).click();
  await page.getByLabel('Option List').getByText('Work From Home').click();
  await page.getByRole('combobox', { name: 'Select Work From Home Manager' }).click();
  await page.getByText('SD302262 - saii Pavan Dinesh').click();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('textbox').fill('2026-08-31');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('cell', { name: '28 Aug' }).click();
  await page.getByRole('columnheader', { name: 'Effective From' }).click();
  await page.getByRole('columnheader', { name: 'Allocation Type' }).click();
  await page.getByRole('columnheader', { name: 'Allocated Location' }).click();
  await page.getByRole('columnheader', { name: 'Allocated Location' }).click();
  await page.getByRole('columnheader', { name: 'Allocated Manager' }).click();
  await page.getByRole('columnheader', { name: 'Allocated By' }).click();
  await page.getByRole('columnheader', { name: 'Status' }).click();
  await page.getByRole('cell', { name: 'Active', exact: true }).click();
  await page.getByRole('cell', { name: 'Inactive' }).click();
  await page.locator('#sidenav-main-drop > div:nth-child(3)').click();
  await page.goto('https://hrmsqarightlyhr.onpremise.cluster.rightlyhr.com/dashboard/emp');
  await page.locator('#sidenav-main-drop > div:nth-child(3)').click();
  await page.locator('div').filter({ hasText: /^WFH$/ }).first().click();
  await page.locator('div').filter({ hasText: /^Waiting For Approval \(1\)$/ }).first().click();
  await page.locator('div').filter({ hasText: /^Approved \(0\)$/ }).first().click();
  await page.locator('div').filter({ hasText: /^Processed \(18\)$/ }).first().click();
  await page.locator('div').filter({ hasText: /^Rejected \(0\)$/ }).first().click();
  await page.locator('div').filter({ hasText: /^Cancelled \(0\)$/ }).first().click();
  await page.locator('div').filter({ hasText: /^Waiting For Approval \(1\)$/ }).first().click();
  await page.getByRole('combobox', { name: 'Select employee name' }).click();
  await page.getByRole('combobox', { name: 'Select employee name' }).click();
  await page.getByRole('combobox', { name: '2026' }).click();
  await page.locator('div').filter({ hasText: /^WFHBooked0\.5Processed03\.5\/4$/ }).nth(1).click();
  await page.getByRole('button', { name: 'Request WFH' }).click();
  await page.getByRole('textbox', { name: 'Start Date *' }).fill('2026-08-27');
  await page.getByRole('textbox', { name: 'End Date *' }).fill('2026-08-27');
  await page.getByRole('radio', { name: 'Half Day' }).check();
  await page.getByRole('textbox', { name: 'Reason *' }).click();
  await page.getByRole('textbox', { name: 'Reason *' }).fill('Request WFH ');
  await page.getByRole('button', { name: 'Request' }).click();
  await page.getByText('Pending Approvals').click();
  await page.getByText('Pending Approvals').click();
  await page.getByText('Pending Approvals').click();
  await page.getByText('Pending Approvals').click();
  await page.getByText('Pending Approvals').click();
  await page.getByText('Pending Approvals').click();
  await page.getByText('Pending Approvals').click();
  await page.locator('div:nth-child(9) > .btn-group > div > .main-menu-icon').click();
  await page.getByText('Pending Approvals').click();
  await page.getByText('Pending Approvals').click();
  await page.getByText('Time-Off(9)').click();
  await page.getByText('WFH(1)').click();
  await page.getByRole('cell', { name: 'SD302262' }).click();
  await page.getByRole('cell', { name: 'saii Pavan Dinesh Tejaa' }).click();
  await page.getByRole('cell', { name: 'Aug 27,' }).click();
  await page.getByRole('cell', { name: 'First Half' }).click();
  await page.locator('a').nth(5).click();
  await page.getByRole('cell', { name: '-' }).click();
  await page.getByRole('cell', { name: 'Aug 31,' }).click();
  await page.locator('.dropdown > a').click();
  await page.getByRole('link', { name: 'For Your Role (0)' }).click();
  await page.getByRole('link', { name: 'For You (1)' }).click();
  await page.locator('.dropdown > a').click();
  await page.locator('.dropdown > a').click();
  await page.locator('.dropdown > a').click();
  await page.getByRole('cell').filter({ hasText: 'ApproveReject' }).click();
  await page.getByText('Reject').click();
  await page.getByRole('button', { name: 'Rejected' }).click();
  await page.getByRole('button', { name: 'Reject', exact: true }).click();
  await page.getByText('WFH request Rejected').click();
  await page.locator('#sidenav-main-drop > div:nth-child(3)').click();
  await page.locator('app-time-off-tabs').getByText('WFH').click();
  await page.getByText('Rejected (1)').click();
  await page.getByRole('cell', { name: 'Aug 27,' }).click();
  await page.getByRole('cell', { name: 'Aug 27,' }).click();
  await page.getByRole('cell', { name: 'Rejected' }).click();
  await page.getByRole('cell', { name: 'Aug 31,' }).click();
  await page.getByRole('cell').nth(3).click();
  await page.locator('app-info-icon > svg > path').first().click();
  await page.getByRole('textbox', { name: 'Start Date *' }).fill('2026-08-26');
  await page.getByRole('textbox', { name: 'End Date *' }).fill('2026-08-26');
  await page.getByRole('textbox', { name: 'Reason *' }).fill('Request for WFH ');
  await page.goto('https://hrmsqarightlyhr.onpremise.cluster.rightlyhr.com/time-off/wfh/waiting-for-approval');
  await page.locator('div').filter({ hasText: /^Time-Off\(9\)$/ }).first().click();
  await page.locator('a').nth(5).click();
  await page.getByText('WFH(1)').click();
  await page.getByRole('row', { name: 'SD302262 saii Pavan Dinesh' }).getByRole('checkbox').check();
  await page.getByRole('button', { name: 'Approve' }).click();
  await page.getByRole('button', { name: 'Approved' }).click();
  await page.getByRole('button', { name: 'Approve', exact: true }).click();
  await page.getByRole('cell', { name: '1' }).first().click();
  await page.getByRole('cell', { name: '1' }).nth(1).click();
  await page.getByRole('cell', { name: '0' }).click();
  await page.locator('div').filter({ hasText: 'Summary' }).nth(3).click();
  await page.getByRole('columnheader', { name: 'Success Records' }).click();
  await page.getByRole('dialog').click();
  await page.goto('https://hrmsqarightlyhr.onpremise.cluster.rightlyhr.com/pending-approvals/time-off/leaves/for-you');
  await page.locator('li:nth-child(5) > .nav-link > .icon').click();
  await page.getByRole('link', { name: 'For Your Role (0)' }).click();
});