import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://hrmsqasnad.onpremise.cluster.rightlyhr.com/login');
  await page.getByRole('button', { name: 'Add Contract Employee' }).click();
  await page.locator('div').filter({ hasText: /^First Name \*$/ }).click();
  await page.getByRole('textbox', { name: 'Please enter first name' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Please enter first name' }).fill('R');
  await page.getByRole('textbox', { name: 'Please enter first name' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Please enter first name' }).fill('Ravi');
  await page.getByRole('textbox', { name: 'Please enter last name' }).click();
  await page.getByRole('textbox', { name: 'Please enter last name' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Please enter last name' }).fill('C');
  await page.getByRole('textbox', { name: 'Please enter last name' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Please enter last name' }).fill('Chandra');
  await page.getByRole('textbox', { name: 'Please enter personal email ID' }).click();
  await page.getByRole('textbox', { name: 'Please enter personal email ID' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Please enter personal email ID' }).fill('C');
  await page.getByRole('textbox', { name: 'Please enter personal email ID' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Please enter personal email ID' }).fill('Chandra@yopmail.com');
  await page.locator('#pn_id_7').getByRole('button', { name: 'dropdown trigger' }).click();
  await page.getByRole('searchbox').fill('qa');
  await page.getByRole('option', { name: 'QA Tester' }).click();
  await page.getByRole('combobox', { name: 'Please select employment type' }).click();
  await page.getByText('Fresher').click();
  await page.getByRole('combobox', { name: 'Please select location' }).click();
  await page.getByRole('option', { name: 'Hyderabad' }).click();
  await page.locator('#sublocation').getByRole('button', { name: 'dropdown trigger' }).click();
  await page.locator('span').filter({ hasText: 'Jai Hind Enclave Building' }).click();
  await page.getByRole('button', { name: 'Add' }).click();
  await page.getByRole('searchbox', { name: 'Username' }).click();
  await page.getByRole('searchbox', { name: 'Username' }).fill('ravi');
  await page.getByText('Ravi Chandra').click();
  await page.getByRole('button', { name: 'Request for Documents' }).click();
  await page.getByText('Email has been sent').click();
  import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://hrmsqasnad.onpremise.cluster.rightlyhr.com/login');
  await page1.getByText('').click();
  await page1.getByRole('textbox', { name: 'Login' }).fill('ravi.bhanu@yopmail.com');
  await page1.getByTitle('Check Inbox @yopmail.com').click();
  await page1.locator('#refresh').click();
  await page1.locator('#refresh').click();
  const page2Promise = page1.waitForEvent('popup');
  await page1.locator('iframe[name="ifmail"]').contentFrame().getByRole('link', { name: 'Click here' }).click();
  const page2 = await page2Promise;
  await page2.getByRole('button', { name: 'Login' }).click();
  await page2.getByRole('button', { name: 'Go To Application' }).click();
  await page2.getByRole('textbox', { name: 'First Name*' }).click();
  await page2.getByRole('textbox', { name: 'Last Name*' }).click();
  await page2.getByRole('combobox', { name: 'Please select gender' }).click();
  await page2.getByRole('option', { name: 'Male', exact: true }).click();
  await page2.getByRole('combobox', { name: 'Please select salutation' }).click();
  await page2.locator('#salutation_1').click();
  await page2.getByText('Select country').click();
  await page2.locator('lib-country-list').getByRole('textbox').fill('91');
  await page2.getByText('India (भारत)').click();
  await page2.getByText('Bolivia (Plurinational State').click();
  await page2.getByRole('textbox', { name: 'Please enter your mobile' }).fill('7474785687');
  await page2.getByRole('textbox', { name: 'Date Of Birth *' }).fill('1998-10-13');
  await page2.locator('#currentAddressLine1').press('CapsLock');
  await page2.locator('#currentAddressLine1').fill('R');
  await page2.locator('#currentAddressLine1').press('CapsLock');
  await page2.locator('#currentAddressLine1').fill('Road no.49');
  await page2.locator('#currentCity').press('CapsLock');
  await page2.locator('#currentCity').fill('H');
  await page2.locator('#currentCity').press('CapsLock');
  await page2.locator('#currentCity').fill('Hyderabad');
  await page2.locator('#currentState').press('CapsLock');
  await page2.locator('#currentState').fill('T');
  await page2.locator('#currentState').press('CapsLock');
  await page2.locator('#currentState').fill('Telangana');
  await page2.getByRole('textbox', { name: 'Country*' }).press('CapsLock');
  await page2.getByRole('textbox', { name: 'Country*' }).fill('I');
  await page2.getByRole('textbox', { name: 'Country*' }).press('CapsLock');
  await page2.getByRole('textbox', { name: 'Country*' }).fill('India');
  await page2.locator('#currentzipCode').fill('50081');
  await page2.getByRole('textbox', { name: 'Address Line2*' }).press('CapsLock');
  await page2.getByRole('textbox', { name: 'Address Line2*' }).fill('VIP H');
  await page2.getByRole('textbox', { name: 'Address Line2*' }).press('CapsLock');
  await page2.getByRole('textbox', { name: 'Address Line2*' }).fill('VIP Hills');
  await page2.goto('https://preonboardingqasnad.onpremise.cluster.rightlyhr.com/document');
  await page2.getByRole('textbox', { name: 'Document Number*' }).fill('575756756756');
  await page2.getByRole('textbox', { name: 'Document Number*' }).press('CapsLock');
  await page2.getByRole('textbox', { name: 'Document Number*' }).fill('ESFDT4567H');
  await page2.goto('https://preonboardingqasnad.onpremise.cluster.rightlyhr.com/');
  await page.goto('https://hrmsqasnad.onpremise.cluster.rightlyhr.com/personalinfo/personal/basic-info');
  await page.getByText('Job', { exact: true }).click();
  await page.getByRole('img', { name: 'Onboarding Documents' }).click();
  await page.locator('.dropdown > a').first().click();
  await page.getByRole('cell', { name: 'Submitted' }).nth(1).click();
  await page.locator('.dropdown.ng-star-inserted').first().click();
  await page.getByText('Approve').first().click();
  await page.getByRole('button', { name: 'Yes' }).click();
  await page.getByText('Document approved successfully').click();
  await page.locator('.dropdown > a').first().click();
  await page.locator('.dropdown > a').first().click();
  await page.locator('.dropdown > a').first().click();
  await page.getByRole('cell').filter({ hasText: 'ApproveReject' }).first().click();
  await page.getByText('Approve').first().click();
  await page.getByRole('button', { name: 'Yes' }).click();
  await page.getByRole('cell').filter({ hasText: 'ApproveReject' }).first().click();
  await page.getByText('Approve').first().click();
  await page.getByRole('button', { name: 'Yes' }).click();
  await page.getByText('Document approved successfully').click();
  await page.locator('.dropdown.ng-star-inserted').click();
  await page.getByText('Approve').click();
  await page.getByRole('button', { name: 'Yes' }).click();
  await page.getByText('Employees').click();
  await page.getByText('Prospective(0)').click();
  await page.getByRole('searchbox', { name: 'Username' }).fill('RAVI.BH');
  await page.goto('https://hrmsqasnad.onpremise.cluster.rightlyhr.com/employee-management/prospective/contract');
  await page.getByRole('searchbox', { name: 'Username' }).press('CapsLock');
  await page.getByRole('searchbox', { name: 'Username' }).fill('ravi.bhanu');
});
});